# Generated by Django 5.2.8 on 2025-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=15)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("response", models.JSONField()),
            ],
        ),
    ]
