# Generated by Django 5.2.8 on 2025-11-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
        ("tenants", "0010_historicalconsultant_historicallocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_messages",
                to="tenants.tenant",
            ),
        ),
    ]
