/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ClientNavigationBottom: typeof import('./src/components/ClientNavigationBottom.vue')['default']
    ClientNavigationTop: typeof import('./src/components/ClientNavigationTop.vue')['default']
    ClientQuestion: typeof import('./src/components/ClientQuestion.vue')['default']
    ClientQuestionConsultant: typeof import('./src/components/ClientQuestionConsultant.vue')['default']
    ClientSection: typeof import('./src/components/ClientSection.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConsultantQuestion: typeof import('./src/components/ConsultantQuestion.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HelloComponent: typeof import('./src/components/HelloComponent.vue')['default']
    HistoryComponent: typeof import('./src/components/HistoryComponent.vue')['default']
    HistoryItem: typeof import('./src/components/HistoryItem.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconLeftArrowSmall: typeof import('./src/components/icons/IconLeftArrowSmall.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconRightArrow: typeof import('./src/components/icons/IconRightArrow.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MultiChoiceMultiTextQuestion: typeof import('./src/components/questions/MultiChoiceMultiTextQuestion.vue')['default']
    MultipleChoiceQuestion: typeof import('./src/components/questions/MultipleChoiceQuestion.vue')['default']
    MultipleChoiceTextQuestion: typeof import('./src/components/questions/MultipleChoiceTextQuestion.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OpenTextQuestion: typeof import('./src/components/questions/OpenTextQuestion.vue')['default']
    PastVisitsComponent: typeof import('./src/components/PastVisitsComponent.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SingleChoiceDropdownQuestion: typeof import('./src/components/questions/SingleChoiceDropdownQuestion.vue')['default']
    SingleChoiceQuestion: typeof import('./src/components/questions/SingleChoiceQuestion.vue')['default']
    SingleChoiceTextQuestion: typeof import('./src/components/questions/SingleChoiceTextQuestion.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
