// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type Client, type TDataShape, urlSearchParamsBodySerializer } from './client';
import type { CoreApiGetCsrfTokenData, CoreApiGetCsrfTokenResponses, CoreApiLoginViewData, CoreApiLoginViewResponses, CoreApiLogoutViewData, CoreApiLogoutViewResponses, CoreApiAccountData, CoreApiAccountResponses, SureApiGetQuestionnaireData, SureApiGetQuestionnaireResponses, SureApiGetInternalQuestionnaireData, SureApiGetInternalQuestionnaireResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Csrf Token
 */
export const coreApiGetCsrfToken = <ThrowOnError extends boolean = false>(options?: Options<CoreApiGetCsrfTokenData, ThrowOnError>) => {
    return (options?.client ?? client).post<CoreApiGetCsrfTokenResponses, unknown, ThrowOnError>({
        url: '/api/csrf',
        ...options
    });
};

/**
 * Login View
 */
export const coreApiLoginView = <ThrowOnError extends boolean = false>(options: Options<CoreApiLoginViewData, ThrowOnError>) => {
    return (options.client ?? client).post<CoreApiLoginViewResponses, unknown, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/api/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Logout View
 */
export const coreApiLogoutView = <ThrowOnError extends boolean = false>(options?: Options<CoreApiLogoutViewData, ThrowOnError>) => {
    return (options?.client ?? client).post<CoreApiLogoutViewResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/logout',
        ...options
    });
};

/**
 * Account
 */
export const coreApiAccount = <ThrowOnError extends boolean = false>(options?: Options<CoreApiAccountData, ThrowOnError>) => {
    return (options?.client ?? client).post<CoreApiAccountResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/account',
        ...options
    });
};

/**
 * Get Questionnaire
 * Get a questionnaire by its ID.
 */
export const sureApiGetQuestionnaire = <ThrowOnError extends boolean = false>(options: Options<SureApiGetQuestionnaireData, ThrowOnError>) => {
    return (options.client ?? client).get<SureApiGetQuestionnaireResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/sure/questionnaires/{pk}',
        ...options
    });
};

/**
 * Get Internal Questionnaire
 * Get a questionnaire by its ID, including consultant questions.
 */
export const sureApiGetInternalQuestionnaire = <ThrowOnError extends boolean = false>(options: Options<SureApiGetInternalQuestionnaireData, ThrowOnError>) => {
    return (options.client ?? client).get<SureApiGetInternalQuestionnaireResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/sure/internal/questionnaires/{pk}',
        ...options
    });
};
