// This file is auto-generated by @hey-api/openapi-ts

/**
 * CsrfTokenResponse
 */
export type CsrfTokenResponse = {
    /**
     * Csrftoken
     */
    csrfToken: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * AccountResponse
 */
export type AccountResponse = {
    /**
     * Username
     */
    username: string | null;
    /**
     * Is Staff
     */
    is_staff?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * ClientOptionSchema
 */
export type ClientOptionSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the option in the question
     */
    order?: number;
    /**
     * Option Text
     */
    text?: string | null;
    /**
     * Code
     * Unique code for the option
     */
    code: string;
    /**
     * Choices
     */
    choices?: Array<unknown> | null;
    /**
     * Allow Text
     * Allow text input for this option
     */
    allow_text?: boolean;
};

/**
 * ClientQuestionSchema
 */
export type ClientQuestionSchema = {
    /**
     * Options
     */
    options: Array<ClientOptionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the question in the questionnaire
     */
    order?: number;
    /**
     * Code
     * Unique code for the question
     */
    code: string;
    /**
     * Question Text
     */
    question_text: string;
    /**
     * Format
     */
    format?: string;
    /**
     * Validation
     * Regex validation for open text questions
     */
    validation?: string | null;
    /**
     * Show For Options
     * Show this question only if one of these options is selected
     */
    show_for_options: Array<number>;
    /**
     * Copy Paste
     * Allow copy paste for this question
     */
    copy_paste?: boolean;
    /**
     * Do Not Show Directly
     * Do not show this question directly to the client
     */
    do_not_show_directly?: boolean;
};

/**
 * QuestionnaireSchema
 */
export type QuestionnaireSchema = {
    /**
     * Sections
     */
    sections: Array<SectionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     * Name of the questionnaire
     */
    name: string;
};

/**
 * SectionSchema
 */
export type SectionSchema = {
    /**
     * Client Questions
     */
    client_questions: Array<ClientQuestionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the section in the questionnaire
     */
    order?: number;
    /**
     * Title
     * Title of the section
     */
    title: string;
    /**
     * Description
     * Description of the section
     */
    description?: string | null;
};

/**
 * ConsultantOptionSchema
 */
export type ConsultantOptionSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the option in the question
     */
    order?: number;
    /**
     * Option Text
     */
    text?: string | null;
    /**
     * Code
     * Unique code for the option
     */
    code: string;
    /**
     * Choices
     */
    choices?: Array<unknown> | null;
    /**
     * Allow Text
     * Allow text input for this option
     */
    allow_text?: boolean;
};

/**
 * ConsultantQuestionSchema
 */
export type ConsultantQuestionSchema = {
    /**
     * Options
     */
    options: Array<ConsultantOptionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the question in the questionnaire
     */
    order?: number;
    /**
     * Code
     * Unique code for the question
     */
    code: string;
    /**
     * Question Text
     */
    question_text: string;
    /**
     * Format
     */
    format?: string;
    /**
     * Validation
     * Regex validation for open text questions
     */
    validation?: string | null;
    /**
     * Copy Paste
     * Allow copy paste for this question
     */
    copy_paste?: boolean;
};

/**
 * InternalQuestionnaireSchema
 */
export type InternalQuestionnaireSchema = {
    /**
     * Sections
     */
    sections: Array<SectionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     * Name of the questionnaire
     */
    name: string;
    /**
     * Consultant Questions
     */
    consultant_questions: Array<ConsultantQuestionSchema>;
};

/**
 * CaseListingSchema
 */
export type CaseListingSchema = {
    /**
     * Location
     */
    location: string;
    /**
     * Client
     */
    client: string | null;
    /**
     * Last Modified At
     */
    last_modified_at: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Case
     */
    case: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Status
     */
    status?: string;
};

/**
 * ClientAnswerSchema
 */
export type ClientAnswerSchema = {
    /**
     * Choices
     */
    choices: Array<number>;
    /**
     * Texts
     */
    texts: Array<string>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Question
     */
    question: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User
     * The user who recorded the answer (consultant)
     */
    user?: number | null;
};

/**
 * ConsultantAnswerSchema
 */
export type ConsultantAnswerSchema = {
    /**
     * Choices
     */
    choices: Array<number>;
    /**
     * Texts
     */
    texts: Array<string>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Question
     */
    question: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User
     * The user who recorded the answer (consultant)
     */
    user?: number | null;
};

/**
 * CaseHistory
 */
export type CaseHistory = {
    /**
     * Client Answers
     */
    client_answers: Array<ClientAnswerSchema>;
    /**
     * Consultant Answers
     */
    consultant_answers: Array<ConsultantAnswerSchema>;
};

/**
 * SubmitCaseResponse
 */
export type SubmitCaseResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string> | null;
};

/**
 * AnswerSchema
 */
export type AnswerSchema = {
    /**
     * Questionid
     */
    questionId: number;
    /**
     * Choices
     */
    choices: Array<ChoiceSchema>;
};

/**
 * ChoiceSchema
 */
export type ChoiceSchema = {
    /**
     * Code
     */
    code: string;
    /**
     * Text
     */
    text: string;
};

/**
 * SubmitCaseSchema
 */
export type SubmitCaseSchema = {
    /**
     * Answers
     */
    answers: Array<AnswerSchema>;
};

/**
 * CreateCaseResponse
 */
export type CreateCaseResponse = {
    /**
     * Link
     */
    link: string;
    /**
     * Case Id
     */
    case_id: string;
};

/**
 * CreateCaseSchema
 */
export type CreateCaseSchema = {
    /**
     * Location Id
     */
    location_id: number;
    /**
     * Questionnaire Id
     */
    questionnaire_id: number;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * External Id
     */
    external_id?: string | null;
};

/**
 * Input
 */
export type Input = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number | null;
};

/**
 * PagedCaseListingSchema
 */
export type PagedCaseListingSchema = {
    /**
     * Items
     */
    items: Array<CaseListingSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * CaseFilters
 */
export type CaseFilters = {
    search: FilterData;
    case: FilterData;
    client_id: FilterData;
    tags: FilterOperator;
    location: FilterData;
    status: FilterData;
    last_modified_at: FilterOperator;
};

/**
 * FilterData
 */
export type FilterData = {
    /**
     * Value
     */
    value: unknown | null;
    matchMode: MatchModes;
};

/**
 * FilterOperator
 */
export type FilterOperator = {
    operator: Operator;
    /**
     * Constraints
     */
    constraints: Array<FilterData>;
};

/**
 * MatchModes
 */
export type MatchModes = 'startsWith' | 'contains' | 'notContains' | 'endsWith' | 'equals' | 'notEquals' | 'in' | 'lt' | 'lte' | 'gt' | 'gte' | 'between' | 'dateIs' | 'dateIsNot' | 'dateBefore' | 'dateAfter';

/**
 * Operator
 */
export type Operator = 'and' | 'or';

/**
 * OptionSchema
 */
export type OptionSchema = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * QuestionnaireListingSchema
 */
export type QuestionnaireListingSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     * Name of the questionnaire
     */
    name: string;
};

/**
 * LocationSchema
 */
export type LocationSchema = {
    tenant: TenantSchema;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * TenantSchema
 */
export type TenantSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * TagSchema
 */
export type TagSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Username
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

export type CoreApiGetCsrfTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/csrf';
};

export type CoreApiGetCsrfTokenResponses = {
    /**
     * OK
     */
    200: CsrfTokenResponse;
};

export type CoreApiGetCsrfTokenResponse = CoreApiGetCsrfTokenResponses[keyof CoreApiGetCsrfTokenResponses];

export type CoreApiLoginViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Username
         */
        username: string;
        /**
         * Password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/login';
};

export type CoreApiLoginViewErrors = {
    /**
     * Unknown Status Code
     */
    4: LoginResponse;
};

export type CoreApiLoginViewError = CoreApiLoginViewErrors[keyof CoreApiLoginViewErrors];

export type CoreApiLoginViewResponses = {
    /**
     * Unknown Status Code
     */
    2: LoginResponse;
};

export type CoreApiLoginViewResponse = CoreApiLoginViewResponses[keyof CoreApiLoginViewResponses];

export type CoreApiLogoutViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type CoreApiLogoutViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CoreApiAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type CoreApiAccountResponses = {
    /**
     * OK
     */
    200: AccountResponse;
};

export type CoreApiAccountResponse = CoreApiAccountResponses[keyof CoreApiAccountResponses];

export type SureApiGetCaseQuestionnaireData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/questionnaire/';
};

export type SureApiGetCaseQuestionnaireResponses = {
    /**
     * OK
     */
    200: QuestionnaireSchema;
};

export type SureApiGetCaseQuestionnaireResponse = SureApiGetCaseQuestionnaireResponses[keyof SureApiGetCaseQuestionnaireResponses];

export type SureApiGetCaseInternalData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/internal/';
};

export type SureApiGetCaseInternalResponses = {
    /**
     * OK
     */
    200: InternalQuestionnaireSchema;
};

export type SureApiGetCaseInternalResponse = SureApiGetCaseInternalResponses[keyof SureApiGetCaseInternalResponses];

export type SureApiGetVisitData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/visit/';
};

export type SureApiGetVisitResponses = {
    /**
     * OK
     */
    200: CaseListingSchema;
};

export type SureApiGetVisitResponse = SureApiGetVisitResponses[keyof SureApiGetVisitResponses];

export type SureApiGetVisitClientAnswersData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/visit/client-answers/';
};

export type SureApiGetVisitClientAnswersResponses = {
    /**
     * Response
     * OK
     */
    200: Array<ClientAnswerSchema>;
};

export type SureApiGetVisitClientAnswersResponse = SureApiGetVisitClientAnswersResponses[keyof SureApiGetVisitClientAnswersResponses];

export type SureApiGetVisitConsultantAnswersData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/visit/consultant-answers/';
};

export type SureApiGetVisitConsultantAnswersResponses = {
    /**
     * Response
     * OK
     */
    200: Array<ConsultantAnswerSchema>;
};

export type SureApiGetVisitConsultantAnswersResponse = SureApiGetVisitConsultantAnswersResponses[keyof SureApiGetVisitConsultantAnswersResponses];

export type SureApiGetVisitHistoryData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/sure/case/{pk}/visit/history/';
};

export type SureApiGetVisitHistoryResponses = {
    /**
     * OK
     */
    200: CaseHistory;
};

export type SureApiGetVisitHistoryResponse = SureApiGetVisitHistoryResponses[keyof SureApiGetVisitHistoryResponses];

export type SureApiSubmitCaseData = {
    body: SubmitCaseSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/submit/';
};

export type SureApiSubmitCaseResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiSubmitCaseResponse = SureApiSubmitCaseResponses[keyof SureApiSubmitCaseResponses];

export type SureApiSubmitConsultantCaseData = {
    body: SubmitCaseSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/consultant/submit/';
};

export type SureApiSubmitConsultantCaseResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiSubmitConsultantCaseResponse = SureApiSubmitConsultantCaseResponses[keyof SureApiSubmitConsultantCaseResponses];

export type SureApiUpdateCaseTagsData = {
    /**
     * Tags
     */
    body: Array<string>;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/tags/';
};

export type SureApiUpdateCaseTagsResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiUpdateCaseTagsResponse = SureApiUpdateCaseTagsResponses[keyof SureApiUpdateCaseTagsResponses];

export type SureApiCreateCaseViewData = {
    body: CreateCaseSchema;
    path?: never;
    query?: never;
    url: '/api/sure/case/create/';
};

export type SureApiCreateCaseViewResponses = {
    /**
     * OK
     */
    200: CreateCaseResponse;
};

export type SureApiCreateCaseViewResponse = SureApiCreateCaseViewResponses[keyof SureApiCreateCaseViewResponses];

export type SureApiGetQuestionnaireData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: number;
    };
    query?: never;
    url: '/api/sure/questionnaires/{pk}/';
};

export type SureApiGetQuestionnaireResponses = {
    /**
     * OK
     */
    200: QuestionnaireSchema;
};

export type SureApiGetQuestionnaireResponse = SureApiGetQuestionnaireResponses[keyof SureApiGetQuestionnaireResponses];

export type SureApiGetInternalQuestionnaireData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: number;
    };
    query?: never;
    url: '/api/sure/internal/questionnaires/{pk}/';
};

export type SureApiGetInternalQuestionnaireResponses = {
    /**
     * OK
     */
    200: InternalQuestionnaireSchema;
};

export type SureApiGetInternalQuestionnaireResponse = SureApiGetInternalQuestionnaireResponses[keyof SureApiGetInternalQuestionnaireResponses];

export type SureApiListCasesData = {
    body: CaseFilters;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number | null;
    };
    url: '/api/sure/cases/';
};

export type SureApiListCasesResponses = {
    /**
     * OK
     */
    200: PagedCaseListingSchema;
};

export type SureApiListCasesResponse = SureApiListCasesResponses[keyof SureApiListCasesResponses];

export type SureApiGetCaseStatusOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sure/case/status/options/';
};

export type SureApiGetCaseStatusOptionsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<OptionSchema>;
};

export type SureApiGetCaseStatusOptionsResponse = SureApiGetCaseStatusOptionsResponses[keyof SureApiGetCaseStatusOptionsResponses];

export type SureApiGetCaseTagsOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sure/case/tags/options/';
};

export type SureApiGetCaseTagsOptionsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<string>;
};

export type SureApiGetCaseTagsOptionsResponse = SureApiGetCaseTagsOptionsResponses[keyof SureApiGetCaseTagsOptionsResponses];

export type SureApiListClientCasesData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number | null;
    };
    url: '/api/sure/client/{pk}/cases/';
};

export type SureApiListClientCasesResponses = {
    /**
     * OK
     */
    200: PagedCaseListingSchema;
};

export type SureApiListClientCasesResponse = SureApiListClientCasesResponses[keyof SureApiListClientCasesResponses];

export type SureApiListQuestionnairesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sure/questionnaires/';
};

export type SureApiListQuestionnairesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<QuestionnaireListingSchema>;
};

export type SureApiListQuestionnairesResponse = SureApiListQuestionnairesResponses[keyof SureApiListQuestionnairesResponses];

export type TenantsApiListLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/locations';
};

export type TenantsApiListLocationsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<LocationSchema>;
};

export type TenantsApiListLocationsResponse = TenantsApiListLocationsResponses[keyof TenantsApiListLocationsResponses];

export type TenantsApiListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/tags';
};

export type TenantsApiListTagsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TagSchema>;
};

export type TenantsApiListTagsResponse = TenantsApiListTagsResponses[keyof TenantsApiListTagsResponses];

export type TenantsApiGetConsultantData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: number;
    };
    query?: never;
    url: '/api/tenants/consultants/{pk}/';
};

export type TenantsApiGetConsultantResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type TenantsApiGetConsultantResponse = TenantsApiGetConsultantResponses[keyof TenantsApiGetConsultantResponses];

export type ClientOptions = {
    baseUrl: string;
};
