// This file is auto-generated by @hey-api/openapi-ts

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * OTPDeviceResponse
 */
export type OtpDeviceResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Config Url
     */
    config_url?: string | null;
};

/**
 * AccountResponse
 */
export type AccountResponse = {
    /**
     * Username
     */
    username: string | null;
    /**
     * Is Staff
     */
    is_staff?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Verified
     */
    verified?: boolean | null;
    /**
     * Otp
     */
    otp?: boolean | null;
    /**
     * Is Trusted
     */
    is_trusted?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * LangSchema
 */
export type LangSchema = {
    /**
     * Lang
     */
    lang?: string | null;
};

/**
 * ClientOptionSchema
 */
export type ClientOptionSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the option in the question
     */
    order?: number;
    /**
     * Option Text
     */
    text?: string | null;
    /**
     * Code
     * Unique code for the option
     */
    code: string;
    /**
     * Choices
     */
    choices?: Array<unknown> | null;
    /**
     * Allow Text
     * Allow text input for this option
     */
    allow_text?: boolean;
    /**
     * Text for Consultant
     * Text to be shown to the consultant when this option is selected
     */
    text_for_consultant?: string | null;
};

/**
 * ClientQuestionSchema
 */
export type ClientQuestionSchema = {
    /**
     * Options
     */
    options: Array<ClientOptionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the question in the questionnaire
     */
    order?: number;
    /**
     * Code
     * Unique code for the question
     */
    code: string;
    /**
     * Question Text
     */
    question_text: string;
    /**
     * Format
     */
    format?: string;
    /**
     * Label
     * Short label for the question
     */
    label?: string | null;
    /**
     * Validation
     * Regex validation for open text questions
     */
    validation?: string | null;
    /**
     * Show For Options
     * Show this question only if one of these options is selected
     */
    show_for_options: Array<number>;
    /**
     * Copy Paste
     * Allow copy paste for this question
     */
    copy_paste?: boolean;
    /**
     * Do Not Show Directly
     * Do not show this question directly to the client
     */
    do_not_show_directly?: boolean;
};

/**
 * QuestionnaireSchema
 */
export type QuestionnaireSchema = {
    /**
     * Sections
     */
    sections: Array<SectionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     * Name of the questionnaire
     */
    name: string;
};

/**
 * SectionSchema
 */
export type SectionSchema = {
    /**
     * Client Questions
     */
    client_questions: Array<ClientQuestionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the section in the questionnaire
     */
    order?: number;
    /**
     * Title
     * Title of the section
     */
    title: string;
    /**
     * Description
     * Description of the section
     */
    description?: string | null;
    /**
     * Label
     * Short label for the section
     */
    label?: string | null;
};

/**
 * StatusSchema
 */
export type StatusSchema = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message?: string | Array<string> | null;
    /**
     * Warnings
     */
    warnings?: Array<string> | null;
};

/**
 * PhoneNumberSchema
 */
export type PhoneNumberSchema = {
    /**
     * Phone Number
     */
    phone_number: string;
};

/**
 * ConnectSchema
 */
export type ConnectSchema = {
    /**
     * Token
     */
    token: string;
    /**
     * Consent
     */
    consent: string;
    /**
     * Phone Number
     */
    phone_number: string;
};

/**
 * ConsultantOptionSchema
 */
export type ConsultantOptionSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the option in the question
     */
    order?: number;
    /**
     * Option Text
     */
    text?: string | null;
    /**
     * Code
     * Unique code for the option
     */
    code: string;
    /**
     * Choices
     */
    choices?: Array<unknown> | null;
    /**
     * Allow Text
     * Allow text input for this option
     */
    allow_text?: boolean;
};

/**
 * ConsultantQuestionSchema
 */
export type ConsultantQuestionSchema = {
    /**
     * Options
     */
    options: Array<ConsultantOptionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Order
     * Order of the question in the questionnaire
     */
    order?: number;
    /**
     * Code
     * Unique code for the question
     */
    code: string;
    /**
     * Question Text
     */
    question_text: string;
    /**
     * Label
     * Short label for the question
     */
    label?: string | null;
    /**
     * Format
     */
    format?: string;
    /**
     * Validation
     * Regex validation for open text questions
     */
    validation?: string | null;
    /**
     * Copy Paste
     * Allow copy paste for this question
     */
    copy_paste?: boolean;
};

/**
 * InternalQuestionnaireSchema
 */
export type InternalQuestionnaireSchema = {
    /**
     * Sections
     */
    sections: Array<SectionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     * Name of the questionnaire
     */
    name: string;
    /**
     * Consultant Questions
     */
    consultant_questions: Array<ConsultantQuestionSchema>;
};

/**
 * CaseListingSchema
 */
export type CaseListingSchema = {
    /**
     * Location
     */
    location: string;
    /**
     * Client
     */
    client: string | null;
    /**
     * Last Modified At
     */
    last_modified_at: string;
    /**
     * External Id
     */
    external_id: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Case
     */
    case: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Status
     */
    status?: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClientAnswerSchema
 */
export type ClientAnswerSchema = {
    /**
     * Choices
     */
    choices: Array<number>;
    /**
     * Texts
     */
    texts: Array<string>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Question
     */
    question: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User
     * The user who recorded the answer (consultant)
     */
    user?: number | null;
};

/**
 * ConsultantAnswerSchema
 */
export type ConsultantAnswerSchema = {
    /**
     * Choices
     */
    choices: Array<number>;
    /**
     * Texts
     */
    texts: Array<string>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Question
     */
    question: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User
     * The user who recorded the answer (consultant)
     */
    user?: number | null;
};

/**
 * CaseHistory
 */
export type CaseHistory = {
    /**
     * Client Answers
     */
    client_answers: Array<FlatClientAnswerSchema>;
    /**
     * Consultant Answers
     */
    consultant_answers: Array<FlatConsultantAnswerSchema>;
    /**
     * Tests
     */
    tests: Array<FlatTestSchema>;
    /**
     * Test Results
     */
    test_results: Array<FlatTestResultSchema>;
    /**
     * Log
     */
    log: Array<LogEntrySchema>;
};

/**
 * FlatClientAnswerSchema
 */
export type FlatClientAnswerSchema = {
    /**
     * Label
     */
    label: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Texts
     */
    texts?: Array<unknown> | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User
     * The user who recorded the answer (consultant)
     */
    user?: number | null;
};

/**
 * FlatConsultantAnswerSchema
 */
export type FlatConsultantAnswerSchema = {
    /**
     * Label
     */
    label: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Texts
     */
    texts?: Array<unknown> | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User
     * The user who recorded the answer (consultant)
     */
    user?: number | null;
};

/**
 * FlatTestResultSchema
 */
export type FlatTestResultSchema = {
    /**
     * Label
     */
    label: string;
    test: FlatTestSchema;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Result Option
     */
    result_option: number;
    /**
     * Note
     * Additional notes about the test result
     */
    note?: string | null;
    /**
     * User
     * The user who recorded the test result (consultant)
     */
    user?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FlatTestSchema
 */
export type FlatTestSchema = {
    /**
     * Label
     */
    label: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Test Kind
     */
    test_kind: number;
    /**
     * Note
     * Additional notes about the test result
     */
    note?: string | null;
    /**
     * User
     * The user who recorded the test
     */
    user?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LogEntrySchema
 */
export type LogEntrySchema = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Label
     */
    label: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * User
     * The user who performed the action
     */
    user?: number | null;
};

/**
 * SubmitCaseResponse
 */
export type SubmitCaseResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string> | null;
};

/**
 * AnswerSchema
 */
export type AnswerSchema = {
    /**
     * Questionid
     */
    questionId: number;
    /**
     * Choices
     */
    choices: Array<ChoiceSchema>;
};

/**
 * ChoiceSchema
 */
export type ChoiceSchema = {
    /**
     * Code
     */
    code: string;
    /**
     * Text
     */
    text: string;
};

/**
 * SubmitCaseSchema
 */
export type SubmitCaseSchema = {
    /**
     * Answers
     */
    answers: Array<AnswerSchema>;
};

/**
 * SubmitTestsSchema
 */
export type SubmitTestsSchema = {
    /**
     * Test Kind Ids
     */
    test_kind_ids: Array<number>;
    /**
     * Free Form Tests
     */
    free_form_tests: Array<string>;
};

/**
 * TestBundleSchema
 */
export type TestBundleSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * TestKindSchema
 */
export type TestKindSchema = {
    /**
     * Test Bundles
     */
    test_bundles: Array<TestBundleSchema>;
    /**
     * Result Options
     */
    result_options: Array<TestResultOptionSchema>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Number
     */
    number: number;
    /**
     * Name
     */
    name: string;
    /**
     * Note
     * Additional notes about the test
     */
    note?: string | null;
    /**
     * Interpretation Needed
     * Does this test kind need interpretation?
     */
    interpretation_needed?: boolean;
};

/**
 * TestResultOptionSchema
 */
export type TestResultOptionSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Test Kind
     */
    test_kind: number;
    /**
     * Label
     */
    label: string;
    /**
     * Color
     * Color associated with this result option (hex code)
     */
    color?: string | null;
    /**
     * Information Text
     * Information text to be sent to the client
     */
    information_text?: string | null;
};

/**
 * TestResultSchema
 */
export type TestResultSchema = {
    /**
     * Result Option
     */
    result_option: number;
    /**
     * Note
     * Additional notes about the test result
     */
    note?: string | null;
    /**
     * User
     * The user who recorded the test result (consultant)
     */
    user?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TestSchema
 */
export type TestSchema = {
    /**
     * Results
     */
    results: Array<TestResultSchema>;
    test_kind: TestKindSchema;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Note
     * Additional notes about the test result
     */
    note?: string | null;
    /**
     * User
     * The user who recorded the test
     */
    user?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FreeFormTestSchema
 */
export type FreeFormTestSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Test Name
     */
    name: string;
    /**
     * User
     * The user who recorded the free form test
     */
    user?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Test Result
     * Result of the free form test
     */
    result?: string | null;
};

/**
 * FreeFormResultSchema
 */
export type FreeFormResultSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Result
     */
    result: string;
};

/**
 * SubmitTestResultsSchema
 */
export type SubmitTestResultsSchema = {
    /**
     * Test Results
     */
    test_results: Array<TestResultInputSchema>;
    /**
     * Free Form Results
     */
    free_form_results: Array<FreeFormResultSchema>;
};

/**
 * TestResultInputSchema
 */
export type TestResultInputSchema = {
    /**
     * Number
     */
    number: number;
    /**
     * Label
     */
    label: string;
    /**
     * Note
     */
    note: string;
};

/**
 * DocumentSchema
 */
export type DocumentSchema = {
    user: UserSchema;
    /**
     * Link
     */
    link: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Document Name
     * Name of the document
     */
    name: string;
    /**
     * Uploaded At
     */
    uploaded_at: string;
    /**
     * Hidden
     * Whether this document is hidden from clients
     */
    hidden?: boolean;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * Tenant
     */
    tenant: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Username
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * DocumentAccessSchema
 */
export type DocumentAccessSchema = {
    /**
     * Link
     */
    link: string;
};

/**
 * NoteSchema
 */
export type NoteSchema = {
    user: UserSchema;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Note
     * Note content
     */
    note: string;
    /**
     * Hidden
     * Whether this note is hidden from clients
     */
    hidden?: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CreateCaseResponse
 */
export type CreateCaseResponse = {
    /**
     * Link
     */
    link: string;
    /**
     * Case Id
     */
    case_id: string;
};

/**
 * CreateCaseSchema
 */
export type CreateCaseSchema = {
    /**
     * Location Id
     */
    location_id: number;
    /**
     * Questionnaire Id
     */
    questionnaire_id: number;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * External Id
     */
    external_id?: string | null;
};

/**
 * Input
 */
export type Input = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number | null;
};

/**
 * PagedCaseListingSchema
 */
export type PagedCaseListingSchema = {
    /**
     * Items
     */
    items: Array<CaseListingSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * CaseFilters
 */
export type CaseFilters = {
    search: FilterData;
    case: FilterData;
    external_id: FilterData;
    client_id: FilterData;
    tags: FilterOperator;
    location: FilterData;
    status: FilterData;
    last_modified_at: FilterOperator;
    created_at: FilterOperator;
};

/**
 * FilterData
 */
export type FilterData = {
    /**
     * Value
     */
    value: unknown | null;
    matchMode: MatchModes;
};

/**
 * FilterOperator
 */
export type FilterOperator = {
    operator: Operator;
    /**
     * Constraints
     */
    constraints: Array<FilterData>;
};

/**
 * MatchModes
 */
export type MatchModes = 'startsWith' | 'contains' | 'notContains' | 'endsWith' | 'equals' | 'notEquals' | 'in' | 'lt' | 'lte' | 'gt' | 'gte' | 'between' | 'dateIs' | 'dateIsNot' | 'dateBefore' | 'dateAfter';

/**
 * Operator
 */
export type Operator = 'and' | 'or';

/**
 * OptionSchema
 */
export type OptionSchema = {
    /**
     * Label
     */
    label: string;
    /**
     * Value
     */
    value: string;
};

/**
 * PagedRelatedCaseSchema
 */
export type PagedRelatedCaseSchema = {
    /**
     * Items
     */
    items: Array<RelatedCaseSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * RelatedCaseSchema
 */
export type RelatedCaseSchema = {
    /**
     * Case Id
     */
    case_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * QuestionnaireListingSchema
 */
export type QuestionnaireListingSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     * Name of the questionnaire
     */
    name: string;
};

/**
 * TestCategorySchema
 */
export type TestCategorySchema = {
    /**
     * Test Kinds
     */
    test_kinds: Array<TestKindSchema>;
    /**
     * Number
     */
    number: number;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * ResultInformationSchema
 */
export type ResultInformationSchema = {
    /**
     * Option
     */
    option: number;
    /**
     * Information Text
     * Detailed information related to this result option
     */
    information_text?: string | null;
};

/**
 * LocationSchema
 */
export type LocationSchema = {
    tenant: TenantSchema;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Opening Hours
     * JSON field to store opening hours.
     */
    opening_hours?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TenantSchema
 */
export type TenantSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Logo
     */
    logo?: string | null;
};

/**
 * TagSchema
 */
export type TagSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * BannerSchema
 */
export type BannerSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Content
     */
    content: string;
    /**
     * Severity
     */
    severity?: string;
};

/**
 * TextsSchema
 */
export type TextsSchema = {
    /**
     * Texts
     */
    texts: {
        [key: string]: string;
    };
    /**
     * Right To Left
     */
    right_to_left: boolean;
    /**
     * Language
     */
    language?: string | null;
};

export type CoreApiLoginViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Username
         */
        username: string;
        /**
         * Password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type CoreApiLoginViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiLoginViewError = CoreApiLoginViewErrors[keyof CoreApiLoginViewErrors];

export type CoreApiLoginViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiLoginViewResponse = CoreApiLoginViewResponses[keyof CoreApiLoginViewResponses];

export type CoreApiLogoutViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Forget
         */
        forget?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type CoreApiLogoutViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CoreApiSetInitialPasswordData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Sesame
         */
        sesame: string;
        /**
         * Email
         */
        email: string;
        /**
         * New Password
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/set-initial-password';
};

export type CoreApiSetInitialPasswordErrors = {
    /**
     * Response
     * Bad Request
     */
    400: Array<string>;
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiSetInitialPasswordError = CoreApiSetInitialPasswordErrors[keyof CoreApiSetInitialPasswordErrors];

export type CoreApiSetInitialPasswordResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiSetInitialPasswordResponse = CoreApiSetInitialPasswordResponses[keyof CoreApiSetInitialPasswordResponses];

export type CoreApiSetupOtpViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Name
         */
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/otp/create-device';
};

export type CoreApiSetupOtpViewErrors = {
    /**
     * Bad Request
     */
    400: LoginResponse;
};

export type CoreApiSetupOtpViewError = CoreApiSetupOtpViewErrors[keyof CoreApiSetupOtpViewErrors];

export type CoreApiSetupOtpViewResponses = {
    /**
     * OK
     */
    200: OtpDeviceResponse;
};

export type CoreApiSetupOtpViewResponse = CoreApiSetupOtpViewResponses[keyof CoreApiSetupOtpViewResponses];

export type CoreApiVerifyOtpViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Token
         */
        token: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/otp/verify-device';
};

export type CoreApiVerifyOtpViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiVerifyOtpViewError = CoreApiVerifyOtpViewErrors[keyof CoreApiVerifyOtpViewErrors];

export type CoreApiVerifyOtpViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiVerifyOtpViewResponse = CoreApiVerifyOtpViewResponses[keyof CoreApiVerifyOtpViewResponses];

export type CoreApiRemoveOtpViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Device Id
         */
        device_id: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/otp/remove-device';
};

export type CoreApiRemoveOtpViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiRemoveOtpViewError = CoreApiRemoveOtpViewErrors[keyof CoreApiRemoveOtpViewErrors];

export type CoreApiRemoveOtpViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiRemoveOtpViewResponse = CoreApiRemoveOtpViewResponses[keyof CoreApiRemoveOtpViewResponses];

export type CoreApiListOtpDevicesViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/otp/devices';
};

export type CoreApiListOtpDevicesViewErrors = {
    /**
     * Bad Request
     */
    400: LoginResponse;
};

export type CoreApiListOtpDevicesViewError = CoreApiListOtpDevicesViewErrors[keyof CoreApiListOtpDevicesViewErrors];

export type CoreApiListOtpDevicesViewResponses = {
    /**
     * Response
     * OK
     */
    200: Array<OtpDeviceResponse>;
};

export type CoreApiListOtpDevicesViewResponse = CoreApiListOtpDevicesViewResponses[keyof CoreApiListOtpDevicesViewResponses];

export type CoreApiGenerateOtpBackupCodesViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/otp/backup-codes';
};

export type CoreApiGenerateOtpBackupCodesViewErrors = {
    /**
     * Bad Request
     */
    400: LoginResponse;
};

export type CoreApiGenerateOtpBackupCodesViewError = CoreApiGenerateOtpBackupCodesViewErrors[keyof CoreApiGenerateOtpBackupCodesViewErrors];

export type CoreApiGenerateOtpBackupCodesViewResponses = {
    /**
     * Response
     * OK
     */
    200: Array<string>;
};

export type CoreApiGenerateOtpBackupCodesViewResponse = CoreApiGenerateOtpBackupCodesViewResponses[keyof CoreApiGenerateOtpBackupCodesViewResponses];

export type CoreApiOtp2FaChallengeViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Token
         */
        token: string;
        /**
         * Remember
         */
        remember?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/auth/otp/2fa-challenge';
};

export type CoreApiOtp2FaChallengeViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiOtp2FaChallengeViewError = CoreApiOtp2FaChallengeViewErrors[keyof CoreApiOtp2FaChallengeViewErrors];

export type CoreApiOtp2FaChallengeViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiOtp2FaChallengeViewResponse = CoreApiOtp2FaChallengeViewResponses[keyof CoreApiOtp2FaChallengeViewResponses];

export type CoreApiChangePasswordViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Old Password
         */
        old_password: string;
        /**
         * New Password
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/set-password';
};

export type CoreApiChangePasswordViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiChangePasswordViewError = CoreApiChangePasswordViewErrors[keyof CoreApiChangePasswordViewErrors];

export type CoreApiChangePasswordViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiChangePasswordViewResponse = CoreApiChangePasswordViewResponses[keyof CoreApiChangePasswordViewResponses];

export type CoreApiAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/account';
};

export type CoreApiAccountResponses = {
    /**
     * OK
     */
    200: AccountResponse;
};

export type CoreApiAccountResponse = CoreApiAccountResponses[keyof CoreApiAccountResponses];

export type SureApiGetCaseQuestionnaireData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/questionnaire/';
};

export type SureApiGetCaseQuestionnaireErrors = {
    /**
     * Forbidden
     */
    403: StatusSchema;
};

export type SureApiGetCaseQuestionnaireError = SureApiGetCaseQuestionnaireErrors[keyof SureApiGetCaseQuestionnaireErrors];

export type SureApiGetCaseQuestionnaireResponses = {
    /**
     * OK
     */
    200: QuestionnaireSchema;
};

export type SureApiGetCaseQuestionnaireResponse = SureApiGetCaseQuestionnaireResponses[keyof SureApiGetCaseQuestionnaireResponses];

export type SureApiSendTokenData = {
    body: PhoneNumberSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/send-token/';
};

export type SureApiSendTokenErrors = {
    /**
     * Bad Request
     */
    400: StatusSchema;
};

export type SureApiSendTokenError = SureApiSendTokenErrors[keyof SureApiSendTokenErrors];

export type SureApiSendTokenResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiSendTokenResponse = SureApiSendTokenResponses[keyof SureApiSendTokenResponses];

export type SureApiConnectCaseData = {
    body: ConnectSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/connect/';
};

export type SureApiConnectCaseErrors = {
    /**
     * Bad Request
     */
    400: StatusSchema;
};

export type SureApiConnectCaseError = SureApiConnectCaseErrors[keyof SureApiConnectCaseErrors];

export type SureApiConnectCaseResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiConnectCaseResponse = SureApiConnectCaseResponses[keyof SureApiConnectCaseResponses];

export type SureApiGetCaseInternalData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/internal/';
};

export type SureApiGetCaseInternalResponses = {
    /**
     * OK
     */
    200: InternalQuestionnaireSchema;
};

export type SureApiGetCaseInternalResponse = SureApiGetCaseInternalResponses[keyof SureApiGetCaseInternalResponses];

export type SureApiGetPhoneNumberData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/phone/';
};

export type SureApiGetPhoneNumberResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiGetPhoneNumberResponse = SureApiGetPhoneNumberResponses[keyof SureApiGetPhoneNumberResponses];

export type SureApiGetVisitData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/visit/';
};

export type SureApiGetVisitResponses = {
    /**
     * OK
     */
    200: CaseListingSchema;
};

export type SureApiGetVisitResponse = SureApiGetVisitResponses[keyof SureApiGetVisitResponses];

export type SureApiGetVisitClientAnswersData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/visit/client-answers/';
};

export type SureApiGetVisitClientAnswersResponses = {
    /**
     * Response
     * OK
     */
    200: Array<ClientAnswerSchema>;
};

export type SureApiGetVisitClientAnswersResponse = SureApiGetVisitClientAnswersResponses[keyof SureApiGetVisitClientAnswersResponses];

export type SureApiGetVisitConsultantAnswersData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/visit/consultant-answers/';
};

export type SureApiGetVisitConsultantAnswersResponses = {
    /**
     * Response
     * OK
     */
    200: Array<ConsultantAnswerSchema>;
};

export type SureApiGetVisitConsultantAnswersResponse = SureApiGetVisitConsultantAnswersResponses[keyof SureApiGetVisitConsultantAnswersResponses];

export type SureApiGetVisitHistoryData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/visit/history/';
};

export type SureApiGetVisitHistoryResponses = {
    /**
     * OK
     */
    200: CaseHistory;
};

export type SureApiGetVisitHistoryResponse = SureApiGetVisitHistoryResponses[keyof SureApiGetVisitHistoryResponses];

export type SureApiSubmitCaseData = {
    body: SubmitCaseSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/submit/';
};

export type SureApiSubmitCaseResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiSubmitCaseResponse = SureApiSubmitCaseResponses[keyof SureApiSubmitCaseResponses];

export type SureApiSubmitConsultantCaseData = {
    body: SubmitCaseSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/consultant/submit/';
};

export type SureApiSubmitConsultantCaseResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiSubmitConsultantCaseResponse = SureApiSubmitConsultantCaseResponses[keyof SureApiSubmitConsultantCaseResponses];

export type SureApiGetCaseTestsData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/tests/';
};

export type SureApiGetCaseTestsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TestSchema>;
};

export type SureApiGetCaseTestsResponse = SureApiGetCaseTestsResponses[keyof SureApiGetCaseTestsResponses];

export type SureApiUpdateCaseTestsData = {
    body: SubmitTestsSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/tests/';
};

export type SureApiUpdateCaseTestsResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiUpdateCaseTestsResponse = SureApiUpdateCaseTestsResponses[keyof SureApiUpdateCaseTestsResponses];

export type SureApiGetCaseFreeFormTestsData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/free-form-tests/';
};

export type SureApiGetCaseFreeFormTestsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<FreeFormTestSchema>;
};

export type SureApiGetCaseFreeFormTestsResponse = SureApiGetCaseFreeFormTestsResponses[keyof SureApiGetCaseFreeFormTestsResponses];

export type SureApiUpdateCaseStatusData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query: {
        /**
         * Status
         */
        status: string;
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/status/';
};

export type SureApiUpdateCaseStatusResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiUpdateCaseStatusResponse = SureApiUpdateCaseStatusResponses[keyof SureApiUpdateCaseStatusResponses];

export type SureApiUpdateCaseTestResultsData = {
    body: SubmitTestResultsSchema;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/tests/results/';
};

export type SureApiUpdateCaseTestResultsResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiUpdateCaseTestResultsResponse = SureApiUpdateCaseTestResultsResponses[keyof SureApiUpdateCaseTestResultsResponses];

export type SureApiUploadDocumentData = {
    /**
     * MultiPartBodyParams
     */
    body: {
        /**
         * File
         */
        file: Blob | File;
        /**
         * Name
         */
        name: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/documents/create';
};

export type SureApiUploadDocumentResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiUploadDocumentResponse = SureApiUploadDocumentResponses[keyof SureApiUploadDocumentResponses];

export type SureApiListDocumentsData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * As Staff
         */
        as_staff?: boolean;
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/documents/';
};

export type SureApiListDocumentsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<DocumentSchema>;
};

export type SureApiListDocumentsResponse = SureApiListDocumentsResponses[keyof SureApiListDocumentsResponses];

export type SureApiSetDocumentHiddenData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Hidden
         */
        hidden: boolean;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
        /**
         * Doc Pk
         */
        doc_pk: number;
    };
    query?: never;
    url: '/api/sure/case/{pk}/documents/{doc_pk}/set-hidden/';
};

export type SureApiSetDocumentHiddenResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiSetDocumentHiddenResponse = SureApiSetDocumentHiddenResponses[keyof SureApiSetDocumentHiddenResponses];

export type SureApiGetDocumentLinkData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
        /**
         * Doc Pk
         */
        doc_pk: number;
    };
    query?: never;
    url: '/api/sure/case/{pk}/documents/{doc_pk}/link/';
};

export type SureApiGetDocumentLinkResponses = {
    /**
     * OK
     */
    200: DocumentAccessSchema;
};

export type SureApiGetDocumentLinkResponse = SureApiGetDocumentLinkResponses[keyof SureApiGetDocumentLinkResponses];

export type SureApiUpdateCaseTagsData = {
    /**
     * Tags
     */
    body: Array<string>;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/tags/';
};

export type SureApiUpdateCaseTagsResponses = {
    /**
     * OK
     */
    200: SubmitCaseResponse;
};

export type SureApiUpdateCaseTagsResponse = SureApiUpdateCaseTagsResponses[keyof SureApiUpdateCaseTagsResponses];

export type SureApiAddCaseNoteData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Content
         */
        content: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/notes/create';
};

export type SureApiAddCaseNoteResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiAddCaseNoteResponse = SureApiAddCaseNoteResponses[keyof SureApiAddCaseNoteResponses];

export type SureApiListCaseNotesData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * As Staff
         */
        as_staff?: boolean;
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/notes/';
};

export type SureApiListCaseNotesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<NoteSchema>;
};

export type SureApiListCaseNotesResponse = SureApiListCaseNotesResponses[keyof SureApiListCaseNotesResponses];

export type SureApiSetCaseNoteHiddenData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Hidden
         */
        hidden: boolean;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
        /**
         * Note Pk
         */
        note_pk: number;
    };
    query?: never;
    url: '/api/sure/case/{pk}/notes/{note_pk}/set-hidden/';
};

export type SureApiSetCaseNoteHiddenResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiSetCaseNoteHiddenResponse = SureApiSetCaseNoteHiddenResponses[keyof SureApiSetCaseNoteHiddenResponses];

export type SureApiSetCaseKeyData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/case/{pk}/set-key/';
};

export type SureApiSetCaseKeyErrors = {
    /**
     * Bad Request
     */
    400: StatusSchema;
};

export type SureApiSetCaseKeyError = SureApiSetCaseKeyErrors[keyof SureApiSetCaseKeyErrors];

export type SureApiSetCaseKeyResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiSetCaseKeyResponse = SureApiSetCaseKeyResponses[keyof SureApiSetCaseKeyResponses];

export type SureApiCreateCaseViewData = {
    body: CreateCaseSchema;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/create/';
};

export type SureApiCreateCaseViewResponses = {
    /**
     * OK
     */
    200: CreateCaseResponse;
};

export type SureApiCreateCaseViewResponse = SureApiCreateCaseViewResponses[keyof SureApiCreateCaseViewResponses];

export type SureApiListCasesData = {
    body: CaseFilters;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number | null;
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/cases/';
};

export type SureApiListCasesResponses = {
    /**
     * OK
     */
    200: PagedCaseListingSchema;
};

export type SureApiListCasesResponse = SureApiListCasesResponses[keyof SureApiListCasesResponses];

export type SureApiGetCaseStatusOptionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/status/options/';
};

export type SureApiGetCaseStatusOptionsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<OptionSchema>;
};

export type SureApiGetCaseStatusOptionsResponse = SureApiGetCaseStatusOptionsResponses[keyof SureApiGetCaseStatusOptionsResponses];

export type SureApiGetCaseTagsOptionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/tags/options/';
};

export type SureApiGetCaseTagsOptionsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<string>;
};

export type SureApiGetCaseTagsOptionsResponse = SureApiGetCaseTagsOptionsResponses[keyof SureApiGetCaseTagsOptionsResponses];

export type SureApiListClientCasesData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number | null;
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/client/{pk}/cases/';
};

export type SureApiListClientCasesResponses = {
    /**
     * OK
     */
    200: PagedRelatedCaseSchema;
};

export type SureApiListClientCasesResponse = SureApiListClientCasesResponses[keyof SureApiListClientCasesResponses];

export type SureApiListQuestionnairesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/questionnaires/';
};

export type SureApiListQuestionnairesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<QuestionnaireListingSchema>;
};

export type SureApiListQuestionnairesResponse = SureApiListQuestionnairesResponses[keyof SureApiListQuestionnairesResponses];

export type SureApiListTestsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/tests/';
};

export type SureApiListTestsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TestCategorySchema>;
};

export type SureApiListTestsResponse = SureApiListTestsResponses[keyof SureApiListTestsResponses];

export type SureApiListTestResultOptionsData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: number;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/tests/{pk}/result-options/';
};

export type SureApiListTestResultOptionsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TestResultOptionSchema>;
};

export type SureApiListTestResultOptionsResponse = SureApiListTestResultOptionsResponses[keyof SureApiListTestResultOptionsResponses];

export type SureApiGetCaseStatusData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/results/{pk}/status/';
};

export type SureApiGetCaseStatusResponses = {
    /**
     * OK
     */
    200: OptionSchema;
};

export type SureApiGetCaseStatusResponse = SureApiGetCaseStatusResponses[keyof SureApiGetCaseStatusResponses];

export type SureApiGetNonSmsResultsData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/results/{pk}/non-sms/';
};

export type SureApiGetNonSmsResultsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TestSchema>;
};

export type SureApiGetNonSmsResultsResponse = SureApiGetNonSmsResultsResponses[keyof SureApiGetNonSmsResultsResponses];

export type SureApiGetClientResultsData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * As Client
         */
        as_client?: boolean;
    };
    url: '/api/sure/results/{pk}/client/';
};

export type SureApiGetClientResultsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TestSchema>;
};

export type SureApiGetClientResultsResponse = SureApiGetClientResultsResponses[keyof SureApiGetClientResultsResponses];

export type SureApiGetClientFreeFormResultsData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/results/{pk}/free-form-client/';
};

export type SureApiGetClientFreeFormResultsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<FreeFormTestSchema>;
};

export type SureApiGetClientFreeFormResultsResponse = SureApiGetClientFreeFormResultsResponses[keyof SureApiGetClientFreeFormResultsResponses];

export type SureApiGetResultInfoData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Key
         */
        key?: string;
    };
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: never;
    url: '/api/sure/results/{pk}/info/';
};

export type SureApiGetResultInfoResponses = {
    /**
     * Response
     * OK
     */
    200: Array<ResultInformationSchema>;
};

export type SureApiGetResultInfoResponse = SureApiGetResultInfoResponses[keyof SureApiGetResultInfoResponses];

export type SureApiPublishCaseResultsData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: string;
    };
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/sure/case/{pk}/publish/';
};

export type SureApiPublishCaseResultsResponses = {
    /**
     * OK
     */
    200: StatusSchema;
};

export type SureApiPublishCaseResultsResponse = SureApiPublishCaseResultsResponses[keyof SureApiPublishCaseResultsResponses];

export type TenantsApiListLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/locations';
};

export type TenantsApiListLocationsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<LocationSchema>;
};

export type TenantsApiListLocationsResponse = TenantsApiListLocationsResponses[keyof TenantsApiListLocationsResponses];

export type TenantsApiListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/tags';
};

export type TenantsApiListTagsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TagSchema>;
};

export type TenantsApiListTagsResponse = TenantsApiListTagsResponses[keyof TenantsApiListTagsResponses];

export type TenantsApiGetTenantData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/tenant';
};

export type TenantsApiGetTenantResponses = {
    /**
     * OK
     */
    200: TenantSchema;
};

export type TenantsApiGetTenantResponse = TenantsApiGetTenantResponses[keyof TenantsApiGetTenantResponses];

export type TenantsApiGetLocationByIdData = {
    body?: never;
    path: {
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/tenants/tenant/{case_id}';
};

export type TenantsApiGetLocationByIdResponses = {
    /**
     * OK
     */
    200: LocationSchema;
};

export type TenantsApiGetLocationByIdResponse = TenantsApiGetLocationByIdResponses[keyof TenantsApiGetLocationByIdResponses];

export type TenantsApiGetConsultantData = {
    body?: never;
    path: {
        /**
         * Pk
         */
        pk: number;
    };
    query?: never;
    url: '/api/tenants/consultants/{pk}/';
};

export type TenantsApiGetConsultantResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type TenantsApiGetConsultantResponse = TenantsApiGetConsultantResponses[keyof TenantsApiGetConsultantResponses];

export type TenantsApiGetBannersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tenants/banners/';
};

export type TenantsApiGetBannersResponses = {
    /**
     * Response
     * OK
     */
    200: Array<BannerSchema>;
};

export type TenantsApiGetBannersResponse = TenantsApiGetBannersResponses[keyof TenantsApiGetBannersResponses];

export type TextsApiListTextsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string | null;
    };
    url: '/api/texts/texts/';
};

export type TextsApiListTextsResponses = {
    /**
     * OK
     */
    200: TextsSchema;
};

export type TextsApiListTextsResponse = TextsApiListTextsResponses[keyof TextsApiListTextsResponses];

export type TextsApiListLanguagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/texts/languages/';
};

export type TextsApiListLanguagesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<[
        string,
        string
    ]>;
};

export type TextsApiListLanguagesResponse = TextsApiListLanguagesResponses[keyof TextsApiListLanguagesResponses];

export type TextsApiReportMissingTextData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Slug
         */
        slug: string;
    };
    path?: never;
    query?: never;
    url: '/api/texts/missing/';
};

export type TextsApiReportMissingTextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};
