# Generated by Django 5.2.6 on 2025-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_consultant_delete_counselor"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="locations",
            field=models.ManyToManyField(
                related_name="consultants", to="tenants.location"
            ),
        ),
    ]
