# Generated by Django 5.2.8 on 2025-11-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="invitation_mail_subject",
            field=models.CharField(
                default="Your new account on SURE",
                help_text="Subject for invitation emails sent to new users.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="invitation_mail_template",
            field=models.TextField(
                default="Hello {{ first_name }},\n\nA new account has been created for you for {{ tentant.name }} on SURE by {{ user.get_full_name }}.\n\nTo set your password and activate your account, please click the following link:\n{{ activation_link }}\n\nIf you did not expect this email, please ignore it.\n\n",
                help_text="Template for invitation emails sent to new users.",
            ),
        ),
    ]
