# Generated by Django 5.2.8 on 2025-11-19 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_tenant_invitation_mail_subject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultant",
            options={"ordering": ["user__last_name", "user__first_name"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="InformationBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                            ("secondary", "Secondary"),
                            ("contrast", "Contrast"),
                            ("primary", "Primary"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="information_banners", to="tenants.location"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_banners",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
