# Generated by Django 5.2.8 on 2025-11-19 10:27

from django.db import migrations, models

import tenants.models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_alter_consultant_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="opening_hours",
            field=models.JSONField(
                blank=True,
                default=tenants.models.default_opening_hours,
                help_text="JSON field to store opening hours.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
        ),
    ]
