# Generated by Django 5.2.8 on 2025-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0029_alter_clientanswer_texts_and_more"),
        ("tenants", "0007_location_address_location_opening_hours_tenant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="excluded_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="These questions will not be asked for cases at this center.",
                related_name="excluded_in_centers",
                to="sure.clientquestion",
                verbose_name="Excluded Questions at this center.",
            ),
        ),
    ]
