# Generated by Django 5.2.8 on 2025-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0030_resultinformation_visitdocument_visitlog_visitnote"),
        ("tenants", "0008_location_excluded_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="excluded_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="These questions will not be asked for cases at this center.",
                limit_choices_to={"optional_for_centers": True},
                related_name="excluded_in_centers",
                to="sure.clientquestion",
                verbose_name="Excluded Questions at this center.",
            ),
        ),
    ]
