# Generated by Django 5.2.8 on 2025-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_historicaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
