# Generated by Django 5.2.8 on 2025-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0038_clientquestion_extra_for_centers_and_more"),
        ("tenants", "0012_historicallocation_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="included_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="These questions will be asked for cases at this center.",
                limit_choices_to={"extra_for_centers": True},
                related_name="included_in_centers",
                to="sure.clientquestion",
                verbose_name="Included Questions at this center.",
            ),
        ),
    ]
