# Generated by Django 5.2.8 on 2025-12-10 11:39

from django.db import migrations, models

import tenants.models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0039_clientoption_choices_de_clientoption_choices_en_and_more"),
        ("tenants", "0013_location_included_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallocation",
            name="opening_hours",
            field=models.JSONField(
                blank=True,
                default=tenants.models.default_opening_hours,
                help_text="JSON field to store opening hours. These are displayed to clients and used to prevent SMS sending outside opening hours.",
                null=True,
                validators=[tenants.models.validate_opening_hours],
            ),
        ),
        migrations.AlterField(
            model_name="historicallocation",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number displayed to clients for this location.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="logo",
            field=models.TextField(
                blank=True,
                help_text="Upload a png with white or tranparent background resolution of 250px pixels",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="name",
            field=models.CharField(
                help_text="Name of the tenant organization, which will be displayed to consultants and admins",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the banner expires. If empty, the banner does not expire.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="locations",
            field=models.ManyToManyField(
                help_text="Locations for which this banner is displayed.",
                related_name="information_banners",
                to="tenants.location",
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the banner becomes visible. If empty, the banner is visible immediately.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="severity",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("info", "Info"),
                    ("warn", "Warning"),
                    ("error", "Error"),
                    ("secondary", "Secondary"),
                    ("contrast", "Contrast"),
                    ("primary", "Primary"),
                ],
                default="info",
                help_text="Severity level of the banner, which determines its appearance.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="excluded_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="The selected questions will not be asked for cases at this center.",
                limit_choices_to={"optional_for_centers": True},
                related_name="excluded_in_centers",
                to="sure.clientquestion",
                verbose_name="Not visible questions at this center.",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="included_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="These questions will be asked for cases at this center.",
                limit_choices_to={"extra_for_centers": True},
                related_name="included_in_centers",
                to="sure.clientquestion",
                verbose_name="Visible questions at this center.",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="opening_hours",
            field=models.JSONField(
                blank=True,
                default=tenants.models.default_opening_hours,
                help_text="JSON field to store opening hours. These are displayed to clients and used to prevent SMS sending outside opening hours.",
                null=True,
                validators=[tenants.models.validate_opening_hours],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number displayed to clients for this location.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a png with white or tranparent background resolution of 250px pixels",
                null=True,
                upload_to="tenant_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(
                help_text="Name of the tenant organization, which will be displayed to consultants and admins",
                max_length=255,
            ),
        ),
    ]
