# Generated by Django 5.2.8 on 2025-12-10 13:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0014_alter_historicallocation_opening_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="informationbanner",
            name="content_de",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informationbanner",
            name="content_en",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informationbanner",
            name="content_es",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informationbanner",
            name="content_fr",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informationbanner",
            name="content_it",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="informationbanner",
            name="content_pt",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalInformationBanner",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "content",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.'
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                        null=True,
                    ),
                ),
                (
                    "content_de",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                        null=True,
                    ),
                ),
                (
                    "content_fr",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                        null=True,
                    ),
                ),
                (
                    "content_it",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                        null=True,
                    ),
                ),
                (
                    "content_es",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                        null=True,
                    ),
                ),
                (
                    "content_pt",
                    models.TextField(
                        help_text='Content of the information banner, supports markdown or html: <a href="https://example.com/more-info">More info</a>.',
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                            ("secondary", "Secondary"),
                            ("contrast", "Contrast"),
                            ("primary", "Primary"),
                        ],
                        default="info",
                        help_text="Severity level of the banner, which determines its appearance.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the banner becomes visible. If empty, the banner is visible immediately.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the banner expires. If empty, the banner does not expire.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical information banner",
                "verbose_name_plural": "historical information banners",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
