# Generated by Django 5.2.8 on 2025-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0015_informationbanner_content_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_de",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_en",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_es",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_fr",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_it",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_pt",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_de",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_en",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_es",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_fr",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_it",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_pt",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
    ]
