# Generated by Django 5.2.9 on 2025-12-15 09:29

import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_alter_historicalinformationbanner_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="logo",
            field=models.TextField(
                blank=True,
                help_text="Upload a png with white or tranparent background resolution of 250px pixels",
                max_length=100,
                null=True,
                validators=[django_clamd.validators.validate_file_infection],
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a png with white or tranparent background resolution of 250px pixels",
                null=True,
                upload_to="tenant_logos/",
                validators=[django_clamd.validators.validate_file_infection],
            ),
        ),
    ]
