# Generated by Django 5.2.9 on 2025-12-16 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tenants.models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0017_alter_historicaltenant_logo_alter_tenant_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=tenants.models.generate_name, max_length=30
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=tenants.models.generate_token, max_length=80
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
