# Generated by Django 6.0 on 2025-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0018_apitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_de",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_en",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_es",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_fr",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_it",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinformationbanner",
            name="content_pt",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_de",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_en",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_es",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_fr",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_it",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="content_pt",
            field=models.TextField(
                help_text='Content of the information banner, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.',
                null=True,
            ),
        ),
    ]
