# Generated by Django 6.0.1 on 2026-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0019_alter_historicalinformationbanner_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="inactive",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this consultant should be treated as inactive.",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultant",
            name="inactive",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this consultant should be treated as inactive.",
            ),
        ),
        migrations.AlterField(
            model_name="informationbanner",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations for which this banner is displayed.",
                related_name="information_banners",
                to="tenants.location",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="available_in",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="tenants.location"
            ),
        ),
    ]
