# Generated by Django 6.0.1 on 2026-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0020_consultant_inactive_historicalconsultant_inactive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="invitation_mail_template",
            field=models.TextField(
                default="Hello {{ first_name }},\n\nA new account has been created for you for {{ tenant.name }} on SURE by {{ user.get_full_name }}.\n\nTo set your password and activate your account, please click the following link:\n{{ activation_link }}\n\nImportant: This link is only valid for creating an account. Afterwards, you must always log in via www.stay-sure.ch/login. If you did not expect this email, please ignore it.\n",
                help_text="Template for invitation emails sent to new users.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="invitation_mail_template",
            field=models.TextField(
                default="Hello {{ first_name }},\n\nA new account has been created for you for {{ tenant.name }} on SURE by {{ user.get_full_name }}.\n\nTo set your password and activate your account, please click the following link:\n{{ activation_link }}\n\nImportant: This link is only valid for creating an account. Afterwards, you must always log in via www.stay-sure.ch/login. If you did not expect this email, please ignore it.\n",
                help_text="Template for invitation emails sent to new users.",
            ),
        ),
    ]
