# Generated by Django 6.0.1 on 2026-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0021_alter_historicaltenant_invitation_mail_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="reminder_text",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="reminder_text",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
    ]
