# Generated by Django 6.0.1 on 2026-01-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0022_historicallocation_reminder_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="reminder_text_de",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="reminder_text_en",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="reminder_text_es",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="reminder_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="reminder_text_it",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="reminder_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Additional text to include in reminder notifications sent to clients.",
                null=True,
            ),
        ),
    ]
