# Generated by Django 6.0.2 on 2026-02-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0024_historicallocation_reminder_text_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "content",
                    models.TextField(
                        help_text='Content of the advertisement, supports markdown or html: <a target="_blank" href="https://www.markdownguide.org/basic-syntax/">More info</a>.'
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                            ("secondary", "Secondary"),
                            ("contrast", "Contrast"),
                            ("primary", "Primary"),
                        ],
                        default="info",
                        help_text="Severity level of the advertisement, which determines its appearance.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the advertisement becomes visible. If empty, the advertisement is visible immediately.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the advertisement expires. If empty, the advertisement does not expire.",
                        null=True,
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Locations for which this advertisement is displayed.",
                        related_name="advertisements",
                        to="tenants.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
