# Generated by Django 6.0.2 on 2026-02-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0026_advertisement_content_de_advertisement_content_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="severity",
        ),
        migrations.RemoveField(
            model_name="historicaladvertisement",
            name="severity",
        ),
    ]
