"""Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path

import sentry_sdk
from django.urls import reverse_lazy
from environ import Env

env = Env()

MODELTRANSLATION_CUSTOM_FIELDS = ["ArrayField"]

sentry_sdk.init(
    dsn="https://f23eef026dedb9d752fc45fc961f71a0@sentry.d-o.li/5",
    send_default_pii=True,
    traces_sample_rate=1.0,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default="secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "sure.apps.SureConfig",
    "unfold.apps.BasicAppConfig",
    "unfold.contrib.constance",
    "constance",
    "texts",
    "guard",
    "sms",
    "ninja",
    "django_clamd",
    "colorfield",
    "modeltranslation",
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.simple_history",
    "tenants.apps.TenantsConfig",
    "simple_history",
    # "django.contrib.admin",
    "sure.apps.SureAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",
    "whitenoise.runserver_nostatic",
    "django_celery_results",
    "django_celery_beat",
    "django.contrib.postgres",
    "health_check",
    "health_check.db",
    "health_check.cache",
    "health_check.storage",
    "health_check.contrib.migrations",
    "health_check.contrib.celery",
    "health_check.contrib.redis",
    "health_check.contrib.psutil",
    "crispy_forms",
    "django_otp",
    "django_agent_trust",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_hotp",
    "django_otp.plugins.otp_static",
    "axes",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_agent_trust.middleware.AgentMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "guard.middleware.NotFoundRateLimitMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db(default="psql://postgres:postgres@db:5432/postgres"),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

KEY_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 6,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("de", "German"),
    ("fr", "French"),
    ("it", "Italian"),
    ("es", "Spanish"),
    ("pt", "Portuguese"),
]
MODELTRANSLATION_DEFAULT_LANGUAGE = "en"


TIME_ZONE = env.str("TIME_ZONE", default="Europe/Zurich")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static/"


STATICFILES_DIRS = [BASE_DIR / "frontend/dist", BASE_DIR / "frontend/public"]

DJANGO_VITE = {
    "default": {
        "dev_mode": env.bool("VITE_DEV_MODE", default=DEBUG),
        "dev_server_port": env("DJANGO_VITE_DEV_SERVER_PORT", default="5173"),
        "manifest_path": BASE_DIR / "frontend/dist/manifest.json",
    }
}

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": env.str("S3_ACCESS_KEY", default=""),
            "secret_key": env.str("S3_SECRET_KEY", default=""),
            "bucket_name": env.str("S3_BUCKET_NAME", default=""),
            "querystring_auth": True,
            "file_overwrite": True,
            "region_name": env.str("S3_REGION", default="us-east-1"),
            "endpoint_url": env.str("S3_ENDPOINT", ""),
            # "custom_domain": env.str("S3_DOMAIN", ""),
            "addressing_style": "auto",
        },
    },
}


def immutable_file_test(_, url):
    """Determine if file is immutable and should be cached forever."""
    # Match vite (rollup)-generated hashes, à la, `some_file-CSliV9zW.js`
    return re.match(r"^.+[.-][0-9a-zA-Z_-]{8,12}\..+$", url)


WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REDIS_USER = env.str("REDIS_USER", default="default")
REDIS_PASSWORD = env.str("REDIS_PASSWORD", default="password")

REDIS_HOST = env.str("REDIS_HOST", default="redis")
REDIS_PORT = env.int("REDIS_PORT", default=6379)

REDIS_URL = f"redis://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL + "/0",
    }
}

CELERY_BROKER_URL = REDIS_URL + "/1"

CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_RESULT_EXTENDED = True
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24 * 30


HEALTH_CHECK = {
    "DISK_USAGE_MAX": 90,
    "MEMORY_MIN": 100,  # in MB
    "SUBSETS": {
        "startup-probe": ["MigrationsHealthCheck", "DatabaseBackend"],
        "liveness-probe": ["DatabaseBackend"],
    },
}

CONSTANCE_REDIS_CONNECTION = REDIS_URL + "/2"

# SURE Settings

DEFAULT_REGION = env.str("DEFAULT_REGION", default="CH")
SITE_URL = env.str("SITE_URL", default="http://localhost:8000")

UNFOLD = {
    "SITE_TITLE": "Administration",
    "SITE_HEADER": "SURE",
    "SITE_SUBHEADER": "SURE Administration",
    "SITE_SYMBOL": "health_metrics",
    "SHOW_LANGUAGES": True,
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "de": "🇩🇪",
                "fr": "🇫🇷",
                "it": "🇮🇹",
                "es": "🇪🇸",
                "pt": "🇵🇹",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "command_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Questionnaire",
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Questionnaires",
                        "icon": "edit_document",
                        "link": reverse_lazy("admin:sure_questionnaire_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Client questions",
                        "icon": "quiz",
                        "link": reverse_lazy("admin:sure_clientquestion_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Client options",
                        "icon": "checklist",
                        "link": reverse_lazy("admin:sure_clientoption_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Sections",
                        "icon": "vertical_split",
                        "link": reverse_lazy("admin:sure_section_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Consultant questions",
                        "icon": "quiz",
                        "link": reverse_lazy(
                            "admin:sure_consultantquestion_changelist"
                        ),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": "Tests",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Tests",
                        "icon": "lab_research",
                        "link": reverse_lazy("admin:sure_testkind_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Test categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:sure_testcategory_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Test bundles",
                        "icon": "stack",
                        "link": reverse_lazy("admin:sure_testbundle_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Test results",
                        "icon": "stacked_bar_chart",
                        "link": reverse_lazy("admin:sure_testresultoption_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Result information",
                        "icon": "info",
                        "link": reverse_lazy("admin:sure_resultinformation_changelist"),
                    },
                ],
            },
            {
                "title": "Tenants",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Tenants",
                        "icon": "apartment",
                        "link": reverse_lazy("admin:tenants_tenant_changelist"),
                    },
                    {
                        "title": "Locations",
                        "icon": "location_on",
                        "link": reverse_lazy("admin:tenants_location_changelist"),
                    },
                    {
                        "title": "Consultants",
                        "icon": "stethoscope",
                        "link": reverse_lazy("admin:tenants_consultant_changelist"),
                    },
                    {
                        "title": "Information Banners",
                        "icon": "announcement",
                        "link": reverse_lazy(
                            "admin:tenants_informationbanner_changelist"
                        ),
                    },
                    {
                        "title": "Tags",
                        "icon": "label",
                        "link": reverse_lazy("admin:tenants_tag_changelist"),
                    },
                    {
                        "title": "SMS Logs",
                        "icon": "sms",
                        "link": reverse_lazy("admin:sms_smsmessage_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": "Texts",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Text Entries",
                        "icon": "translate",
                        "link": reverse_lazy("admin:texts_text_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": "Export",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Data Export",
                        "icon": "file_download",
                        "link": reverse_lazy("admin:sure_visitexport_changelist"),
                    }
                ],
            },
            {
                "title": "Security",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Blocked Users",
                        "icon": "block",
                        "link": reverse_lazy(
                            "admin:guard_blockedidentifier_changelist"
                        ),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Login Attempts",
                        "icon": "login",
                        "link": reverse_lazy("admin:axes_accessattempt_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Access Logs",
                        "icon": "security",
                        "link": reverse_lazy("admin:axes_accesslog_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Failed logins",
                        "icon": "error",
                        "link": reverse_lazy("admin:axes_accessfailurelog_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Guard",
                        "icon": "shield",
                        "link": reverse_lazy(
                            "admin:guard_protectedendpoint_changelist"
                        ),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(97.7% .014 25)",
            "100": "oklch(94.6% .033 25)",
            "200": "oklch(90.2% .063 25)",
            "300": "oklch(82.7% .119 25)",
            "400": "oklch(71.4% .203 25)",
            "500": "oklch(62.7% .265 25)",
            "600": "oklch(55.8% .288 25)",
            "700": "oklch(49.6% .265 25)",
            "800": "oklch(43.8% .218 25)",
            "900": "oklch(38.1% .176 25)",
            "950": "oklch(29.1% .149 25)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-900)",  # text-base-900
            "important-dark": "var(--color-base-100)",  # text-base-100
        },
    },
    "COMMAND": {
        "search_models": True,  # Search models in command search
    },
    "DASHBOARD_CALLBACK": "sure.cases.dashboard_callback",
}

CRISPY_TEMPLATE_PACK = "unfold_crispy"

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]


SESAME_MAX_AGE = env.int("SESAME_MAX_AGE", default=60 * 60 * 24)  # 1 day in seconds


AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "sesame.backends.ModelBackend",
]


EMAIL_CONFIG = env.email_url("EMAIL_URL", default="smtp://user@:password@localhost:25")

vars().update(EMAIL_CONFIG)

SERVER_EMAIL = env("SERVER_EMAIL", default="root@localhost")

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=SERVER_EMAIL)

EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

CONSTANCE_CONFIG = {
    "TWO_FA_REMINDER_SUBJECT": (
        "2FA Setup Reminder",
        "Subject of the 2FA setup reminder email.",
    ),
    "TWO_FA_REMINDER_EMAIL_TEMPLATE": (
        "Hello {{ user.get_full_name }}, ",
        "Template for the 2FA setup reminder email.",
    ),
    "PASSWORD_RESET_EMAIL_TEMPLATE": (
        "{{activation_link}}",
        "Template for the password reset email.",
    ),
    "PASSWORD_RESET_EMAIL_SUBJECT": (
        "Password Reset",
        "Subject of the password reset email.",
    ),
    "TWO_FA_RESET_EMAIL_SUBJECT": (
        "2FA Reset Notification",
        "Subject of the 2FA reset notification email.",
    ),
    "TWO_FA_RESET_EMAIL_TEMPLATE": (
        "Hello {{ user.get_full_name }}, your 2FA has been reset by {{ admin.get_full_name }}.",
        "Template for the 2FA reset notification email.",
    ),
}

OTP_TOTP_ISSUER = env.str("OTP_TOTP_ISSUER", default="SURE")
OTP_TOTP_IMAGE = env.str("OTP_TOTP_IMAGE", default="")


CASE_CONNECTION_WINDOW_MINUTES = env.int("CASE_CONNECTION_WINDOW_MINUTES", default=60)
TOKEN_VALIDITY_MINUTES = env.int("TOKEN_VALIDITY_MINUTES", default=30)

SMSUP_API_TOKEN = env.str("SMSUP_API_TOKEN", default="")

SIMULATE_SMS = env.bool("SIMULATE_SMS", default=False)

TOKEN_RESEND_INTERVAL_MINUTES = env.int(
    "TOKEN_RESEND_INTERVAL_MINUTES", default=0 if DEBUG else 3
)

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

MAX_KEY_LENGTH = env.int("MAX_KEY_LENGTH", default=512)

DEEPL_API_KEY = env.str("DEEPL_API_KEY", default="")

SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0 if DEBUG else 3600)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

AXES_IPWARE_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "REMOTE_ADDR",
]


AXES_FAILURE_LIMIT = env.int("AXES_FAILURE_LIMIT", default=8)
AXES_COOLOFF_TIME = env.int("AXES_COOLOFF_TIME", default=1)  # in hours
AXES_SENSITIVE_PARAMETERS = ["password", "new_password", "username", "sesame"]
AXES_VERBOSE = DEBUG


CLAMD_SOCKET = ""
CLAMD_USE_TCP = True
CLAMD_TCP_SOCKET = env.int("CLAMD_TCP_SOCKET", default=3310)
CLAMD_TCP_ADDR = env.str("CLAMD_TCP_ADDR", default="127.0.0.1")

CLAMD_FAIL_BY_DEFAULT = True
