# Generated by Django 5.2.6 on 2025-11-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedidentifier",
            name="identifier",
            field=models.CharField(max_length=255),
        ),
    ]
