# Generated by Django 5.2.8 on 2025-11-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guard", "0002_alter_blockedidentifier_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedendpoint",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
