# Generated by Django 5.2.8 on 2025-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("context", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_de", models.TextField(null=True)),
                ("content_fr", models.TextField(null=True)),
                ("content_it", models.TextField(null=True)),
                ("content_es", models.TextField(null=True)),
                ("content_pt", models.TextField(null=True)),
                ("internal", models.BooleanField(default=False)),
            ],
        ),
    ]
