# Generated by Django 5.2.6 on 2025-09-30 11:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
