# Generated by Django 5.2.6 on 2025-09-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0003_alter_connection_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="sure.client",
            ),
        ),
    ]
