# Generated by Django 5.2.6 on 2025-10-03 12:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0004_alter_connection_client"),
        ("tenants", "0002_consultant_delete_counselor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("multiple_choice_with_text", "Multiple Choice with Text"),
                            ("open_text", "Open Text"),
                            ("multi_choice_multi_text", "Multi Choice Multi Text"),
                        ],
                        default="single_choice",
                        max_length=30,
                        verbose_name="Format",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the question",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Short label for the question",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "copy_paste",
                    models.BooleanField(
                        default=False,
                        help_text="Allow copy paste for this question",
                        verbose_name="Copy Paste",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the question in the questionnaire",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsultantQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("multiple_choice_with_text", "Multiple Choice with Text"),
                            ("open_text", "Open Text"),
                            ("multi_choice_multi_text", "Multi Choice Multi Text"),
                        ],
                        default="single_choice",
                        max_length=30,
                        verbose_name="Format",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the question",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Short label for the question",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "copy_paste",
                    models.BooleanField(
                        default=False,
                        help_text="Allow copy paste for this question",
                        verbose_name="Copy Paste",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the question in the questionnaire",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Questionaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the questionnaire",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="Number"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the test category",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ClientOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Option Text")),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the option",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "allow_text",
                    models.BooleanField(
                        default=False,
                        help_text="Allow text input for this option",
                        verbose_name="Allow Text",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the option in the question",
                        verbose_name="Order",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="sure.clientquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "texts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded the answer (consultant)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="sure.clientquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsultantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Option Text")),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the option",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "allow_text",
                    models.BooleanField(
                        default=False,
                        help_text="Allow text input for this option",
                        verbose_name="Allow Text",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the option in the question",
                        verbose_name="Order",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="sure.consultantquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsultantAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "texts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded the answer (consultant)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="sure.consultantquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="questionaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_questions",
                to="sure.questionaire",
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the section in the questionnaire",
                        verbose_name="Order",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the section",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the section",
                        verbose_name="Description",
                    ),
                ),
                (
                    "questionaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="sure.questionaire",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_questions",
                to="sure.section",
            ),
        ),
        migrations.CreateModel(
            name="TestKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="Number"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "interpretation_needed",
                    models.BooleanField(
                        default=False,
                        help_text="Does this test kind need interpretation?",
                        verbose_name="Interpretation Needed",
                    ),
                ),
                (
                    "rapid",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a rapid test?",
                        verbose_name="Rapid",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the test",
                        verbose_name="Note",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_kinds",
                        to="sure.testcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TestBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "test_kinds",
                    models.ManyToManyField(
                        related_name="test_bundles", to="sure.testkind"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResultOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "information_by_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Can this result option be sent by SMS?",
                        verbose_name="Information by SMS",
                    ),
                ),
                (
                    "information_text",
                    models.TextField(
                        blank=True,
                        help_text="Information text to be sent to the client",
                        verbose_name="Information Text",
                    ),
                ),
                (
                    "test_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_options",
                        to="sure.testkind",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the test result",
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded the test result (consultant)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "result_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="sure.testresultoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit",
                        to="sure.case",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="tenants.consultant",
                    ),
                ),
                (
                    "questionaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="sure.questionaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the test result",
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "test_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="sure.testkind",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="sure.visit",
                    ),
                ),
            ],
        ),
    ]
