# Generated by Django 5.2.6 on 2025-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0005_clientquestion_consultantquestion_questionaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientquestion",
            name="do_not_show_directly",
            field=models.BooleanField(
                default=False,
                help_text="Do not show this question directly to the client",
                verbose_name="Do Not Show Directly",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="optional_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is optional for centers",
                verbose_name="Optional for Centers",
            ),
        ),
    ]
