# Generated by Django 5.2.6 on 2025-10-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0006_clientquestion_do_not_show_directly_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientoption",
            options={},
        ),
        migrations.AlterModelOptions(
            name="consultantoption",
            options={},
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_de",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_es",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_fr",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_it",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_pt",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="label_en",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="label_es",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="label_fr",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="label_it",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="label_pt",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="question_text_de",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="question_text_en",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="question_text_es",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="question_text_fr",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="question_text_it",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="question_text_pt",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="text_de",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="text_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="text_es",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="text_fr",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="text_it",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="text_pt",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="label_en",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="label_es",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="label_fr",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="label_it",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="label_pt",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="question_text_de",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="question_text_en",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="question_text_es",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="question_text_fr",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="question_text_it",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="question_text_pt",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="questionaire",
            name="name_de",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="questionaire",
            name="name_en",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="questionaire",
            name="name_es",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="questionaire",
            name="name_fr",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="questionaire",
            name="name_it",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="questionaire",
            name="name_pt",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="description_fr",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="description_it",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="description_pt",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_de",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_en",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_es",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_fr",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_it",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title_pt",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientoption",
            constraint=models.UniqueConstraint(
                fields=("question", "code"),
                name="client_unique_option_code_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="consultantoption",
            constraint=models.UniqueConstraint(
                fields=("question", "code"),
                name="consultant_unique_option_code_per_question",
            ),
        ),
    ]
