# Generated by Django 5.2.6 on 2025-10-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0007_alter_clientoption_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbundle",
            name="name_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testbundle",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testbundle",
            name="name_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testbundle",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testbundle",
            name="name_it",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testbundle",
            name="name_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="name_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="name_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="name_it",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="name_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testkind",
            name="name_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testkind",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testkind",
            name="name_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testkind",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testkind",
            name="name_it",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testkind",
            name="name_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="label_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="label_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="label_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="label_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="label_it",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="testresultoption",
            name="label_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
    ]
