# Generated by Django 5.2.6 on 2025-10-03 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0008_testbundle_name_de_testbundle_name_en_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Questionaire",
            new_name="Questionnaire",
        ),
    ]
