# Generated by Django 5.2.6 on 2025-10-03 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0009_rename_questionaire_questionnaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultantquestion",
            old_name="questionaire",
            new_name="questionnaire",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="questionaire",
            new_name="questionnaire",
        ),
        migrations.RenameField(
            model_name="visit",
            old_name="questionaire",
            new_name="questionnaire",
        ),
    ]
