# Generated by Django 5.2.6 on 2025-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0010_rename_questionaire_consultantquestion_questionnaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="show_for_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="conditional_questions",
                to="sure.clientoption",
                verbose_name="Show For Options, empty = always show",
            ),
        ),
        migrations.AddField(
            model_name="clientquestion",
            name="validation",
            field=models.CharField(
                blank=True,
                help_text="Regex validation for open text questions",
                max_length=255,
                verbose_name="Validation",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="validation",
            field=models.CharField(
                blank=True,
                help_text="Regex validation for open text questions",
                max_length=255,
                verbose_name="Validation",
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientoption",
            name="text_pt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="clientquestion",
            name="format",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("multiple_choice_with_text", "Multiple Choice with Text"),
                    ("open_text", "Open Text"),
                    ("multi_choice_multi_text", "Multi Choice Multi Text"),
                    ("single_choice_with_text", "Single Choice with Text"),
                ],
                default="single_choice",
                max_length=30,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantoption",
            name="text_pt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AlterField(
            model_name="consultantquestion",
            name="format",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("multiple_choice_with_text", "Multiple Choice with Text"),
                    ("open_text", "Open Text"),
                    ("multi_choice_multi_text", "Multi Choice Multi Text"),
                    ("single_choice_with_text", "Single Choice with Text"),
                ],
                default="single_choice",
                max_length=30,
                verbose_name="Format",
            ),
        ),
    ]
