# Generated by Django 5.2.6 on 2025-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0011_clientoption_text_for_consultant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientquestion",
            name="format",
            field=models.CharField(
                choices=[
                    ("single choice", "Single Choice"),
                    ("multiple choice", "Multiple Choice"),
                    (
                        "multiple choice + open text field",
                        "Multiple Choice with Open Text Field",
                    ),
                    ("open text field", "Open Text"),
                    (
                        "multiple choice + multiple open text field",
                        "Multi Choice Multi Text",
                    ),
                    ("single choice + open text field", "Single Choice with Text"),
                ],
                default="single choice",
                max_length=80,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="clientquestion",
            name="show_for_options",
            field=models.ManyToManyField(
                blank=True,
                help_text="Show this question only if one of these options is selected",
                related_name="conditional_questions",
                to="sure.clientoption",
                verbose_name="Show For Options",
            ),
        ),
        migrations.AlterField(
            model_name="consultantquestion",
            name="format",
            field=models.CharField(
                choices=[
                    ("single choice", "Single Choice"),
                    ("multiple choice", "Multiple Choice"),
                    (
                        "multiple choice + open text field",
                        "Multiple Choice with Open Text Field",
                    ),
                    ("open text field", "Open Text"),
                    (
                        "multiple choice + multiple open text field",
                        "Multi Choice Multi Text",
                    ),
                    ("single choice + open text field", "Single Choice with Text"),
                ],
                default="single choice",
                max_length=80,
                verbose_name="Format",
            ),
        ),
    ]
