# Generated by Django 5.2.6 on 2025-10-13 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0012_alter_clientquestion_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientquestion",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
