# Generated by Django 5.2.6 on 2025-10-13 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0013_clientquestion_choices_consultantquestion_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientquestion",
            name="choices",
        ),
        migrations.RemoveField(
            model_name="consultantquestion",
            name="choices",
        ),
        migrations.AddField(
            model_name="clientoption",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
