# Generated by Django 5.2.6 on 2025-10-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0014_remove_clientquestion_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientanswer",
            name="visit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_answers",
                to="sure.visit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultantanswer",
            name="visit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_answers",
                to="sure.visit",
            ),
            preserve_default=False,
        ),
    ]
