# Generated by Django 5.2.6 on 2025-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0015_clientanswer_visit_consultantanswer_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("results_recorded", "Results Recorded"),
                    ("closed", "Closed"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
