# Generated by Django 5.2.6 on 2025-11-07 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0016_visit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
