# Generated by Django 5.2.6 on 2025-11-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0017_visit_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="sure.test",
            ),
            preserve_default=False,
        ),
    ]
