# Generated by Django 5.2.6 on 2025-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0018_testresult_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("results_recorded", "Results Recorded"),
                    ("results_sent", "Results Sent"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
