# Generated by Django 5.2.6 on 2025-11-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0019_alter_visit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="An optional external ID for the case",
                max_length=255,
                verbose_name="External ID",
            ),
        ),
    ]
