# Generated by Django 5.2.6 on 2025-11-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0020_case_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresultoption",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Color associated with this result option (hex code)",
                max_length=7,
                verbose_name="Color",
            ),
        ),
    ]
