# Generated by Django 5.2.6 on 2025-11-14 20:07

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0021_testresultoption_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="sure.visit",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="",
                help_text="Color associated with this result option (hex code)",
                image_field=None,
                max_length=7,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
