# Generated by Django 5.2.6 on 2025-11-14 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0022_alter_test_visit_alter_testresultoption_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded the test",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="test",
            constraint=models.UniqueConstraint(
                fields=("visit", "test_kind"), name="unique_test_per_visit_and_kind"
            ),
        ),
    ]
