# Generated by Django 5.2.8 on 2025-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0023_test_user_test_unique_test_per_visit_and_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientquestion",
            name="format",
            field=models.CharField(
                choices=[
                    ("single choice", "Single Choice"),
                    ("multiple choice", "Multiple Choice"),
                    (
                        "multiple choice + open text field",
                        "Multiple Choice with Open Text Field",
                    ),
                    ("open text field", "Open Text"),
                    ("long text field", "Long Text Field"),
                    (
                        "multiple choice + multiple open text field",
                        "Multi Choice Multi Text",
                    ),
                    ("single choice + open text field", "Single Choice with Text"),
                ],
                default="single choice",
                max_length=80,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="consultantquestion",
            name="format",
            field=models.CharField(
                choices=[
                    ("single choice", "Single Choice"),
                    ("multiple choice", "Multiple Choice"),
                    (
                        "multiple choice + open text field",
                        "Multiple Choice with Open Text Field",
                    ),
                    ("open text field", "Open Text"),
                    ("long text field", "Long Text Field"),
                    (
                        "multiple choice + multiple open text field",
                        "Multi Choice Multi Text",
                    ),
                    ("single choice + open text field", "Single Choice with Text"),
                ],
                default="single choice",
                max_length=80,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("tests_recorded", "Tests Recorded"),
                    ("results_recorded", "Results Recorded"),
                    ("results_sent", "Results Sent"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
