# Generated by Django 5.2.8 on 2025-11-19 10:42

from django.db import migrations, models

import sure.models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0024_alter_clientquestion_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.CharField(
                default=sure.models.generate_case_id,
                max_length=8,
                primary_key=True,
                serialize=False,
                verbose_name="Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.CharField(
                default=sure.models.generate_contact_id,
                max_length=8,
                primary_key=True,
                serialize=False,
                verbose_name="Client ID",
            ),
        ),
    ]
