# Generated by Django 5.2.8 on 2025-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0025_alter_case_id_alter_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                verbose_name="Label",
            ),
        ),
    ]
