# Generated by Django 5.2.8 on 2025-11-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0026_section_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="case",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="sure.case",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="token",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this token is disabled and cannot be used",
                verbose_name="Disabled",
            ),
        ),
    ]
