# Generated by Django 5.2.8 on 2025-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0027_token_case_token_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="key",
            field=models.TextField(
                blank=True,
                help_text="An optional access key for the case data",
                verbose_name="Access Key",
            ),
        ),
    ]
