# Generated by Django 5.2.8 on 2025-11-24 13:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0028_case_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientanswer",
            name="texts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=2000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="consultantanswer",
            name="texts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=2000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the test result",
                max_length=2000,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="testkind",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the test",
                max_length=2000,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the test result",
                max_length=2000,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="testresultoption",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.CreateModel(
            name="FreeFormTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Test Name")),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        help_text="Result of the free form test",
                        max_length=255,
                        verbose_name="Test Result",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "result_recorded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the result was recorded",
                        null=True,
                        verbose_name="Result Recorded At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who recorded the free form test",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_form_tests",
                        to="sure.visit",
                    ),
                ),
            ],
        ),
    ]
