# Generated by Django 5.2.8 on 2025-11-26 21:09

import colorfield.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
import sure.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0030_resultinformation_visitdocument_visitlog_visitnote"),
        ("tenants", "0010_historicalconsultant_historicallocation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitdocument",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Visit Document",
                "verbose_name_plural": "Visit Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="visitnote",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Visit Note",
                "verbose_name_plural": "Visit Notes",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCase",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=sure.models.generate_case_id,
                        max_length=8,
                        verbose_name="Case ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="An optional external ID for the case",
                        max_length=255,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        blank=True,
                        help_text="An optional access key for the case data",
                        verbose_name="Access Key",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Case",
                "verbose_name_plural": "historical Cases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalClientOption",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Option Text"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the option",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "allow_text",
                    models.BooleanField(
                        default=False,
                        help_text="Allow text input for this option",
                        verbose_name="Allow Text",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the option in the question",
                        verbose_name="Order",
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "text_for_consultant",
                    models.CharField(
                        blank=True,
                        help_text="Text to be shown to the consultant when this option is selected",
                        max_length=255,
                        verbose_name="Text for Consultant",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.clientquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical client option",
                "verbose_name_plural": "historical client options",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalClientQuestion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the question",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("single choice", "Single Choice"),
                            ("multiple choice", "Multiple Choice"),
                            (
                                "multiple choice + open text field",
                                "Multiple Choice with Open Text Field",
                            ),
                            ("open text field", "Open Text"),
                            ("long text field", "Long Text Field"),
                            (
                                "multiple choice + multiple open text field",
                                "Multi Choice Multi Text",
                            ),
                            (
                                "single choice + open text field",
                                "Single Choice with Text",
                            ),
                        ],
                        default="single choice",
                        max_length=80,
                        verbose_name="Format",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Short label for the question",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "copy_paste",
                    models.BooleanField(
                        default=False,
                        help_text="Allow copy paste for this question",
                        verbose_name="Copy Paste",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the question in the questionnaire",
                        verbose_name="Order",
                    ),
                ),
                (
                    "validation",
                    models.CharField(
                        blank=True,
                        help_text="Regex validation for open text questions",
                        max_length=255,
                        verbose_name="Validation",
                    ),
                ),
                (
                    "do_not_show_directly",
                    models.BooleanField(
                        default=False,
                        help_text="Do not show this question directly to the client",
                        verbose_name="Do Not Show Directly",
                    ),
                ),
                (
                    "optional_for_centers",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question is optional for centers",
                        verbose_name="Optional for Centers",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical client question",
                "verbose_name_plural": "historical client questions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalConsultantOption",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Option Text"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the option",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "allow_text",
                    models.BooleanField(
                        default=False,
                        help_text="Allow text input for this option",
                        verbose_name="Allow Text",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the option in the question",
                        verbose_name="Order",
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.consultantquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical consultant option",
                "verbose_name_plural": "historical consultant options",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalConsultantQuestion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the question",
                        max_length=100,
                        verbose_name="Code",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("single choice", "Single Choice"),
                            ("multiple choice", "Multiple Choice"),
                            (
                                "multiple choice + open text field",
                                "Multiple Choice with Open Text Field",
                            ),
                            ("open text field", "Open Text"),
                            ("long text field", "Long Text Field"),
                            (
                                "multiple choice + multiple open text field",
                                "Multi Choice Multi Text",
                            ),
                            (
                                "single choice + open text field",
                                "Single Choice with Text",
                            ),
                        ],
                        default="single choice",
                        max_length=80,
                        verbose_name="Format",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Short label for the question",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "copy_paste",
                    models.BooleanField(
                        default=False,
                        help_text="Allow copy paste for this question",
                        verbose_name="Copy Paste",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the question in the questionnaire",
                        verbose_name="Order",
                    ),
                ),
                (
                    "validation",
                    models.CharField(
                        blank=True,
                        help_text="Regex validation for open text questions",
                        max_length=255,
                        verbose_name="Validation",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical consultant question",
                "verbose_name_plural": "historical consultant questions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFreeFormTest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Test Name")),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        help_text="Result of the free form test",
                        max_length=255,
                        verbose_name="Test Result",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "result_recorded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the result was recorded",
                        null=True,
                        verbose_name="Result Recorded At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who recorded the free form test",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical free form test",
                "verbose_name_plural": "historical free form tests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the questionnaire",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Questionnaire",
                "verbose_name_plural": "historical Questionnaires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResultInformation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "information_text",
                    models.TextField(
                        blank=True,
                        help_text="Detailed information related to this result option",
                        max_length=2000,
                        verbose_name="Information Text",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.testresultoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical result information",
                "verbose_name_plural": "historical result informations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSection",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the section in the questionnaire",
                        verbose_name="Order",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the section",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Short label for the section",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the section",
                        verbose_name="Description",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical section",
                "verbose_name_plural": "historical sections",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTestKind",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(db_index=True, verbose_name="Number"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "interpretation_needed",
                    models.BooleanField(
                        default=False,
                        help_text="Does this test kind need interpretation?",
                        verbose_name="Interpretation Needed",
                    ),
                ),
                (
                    "rapid",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a rapid test?",
                        verbose_name="Rapid",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the test",
                        max_length=2000,
                        verbose_name="Note",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.testcategory",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical test kind",
                "verbose_name_plural": "historical test kinds",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTestResultOption",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "information_by_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Can this result option be sent by SMS?",
                        verbose_name="Information by SMS",
                    ),
                ),
                (
                    "information_text",
                    models.TextField(
                        blank=True,
                        help_text="Information text to be sent to the client",
                        max_length=2000,
                        verbose_name="Information Text",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default="",
                        help_text="Color associated with this result option (hex code)",
                        image_field=None,
                        max_length=7,
                        samples=None,
                        verbose_name="Color",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_kind",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.testkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical test result option",
                "verbose_name_plural": "historical test result options",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("client_submitted", "Client Submitted"),
                            ("consultant_submitted", "Consultant Submitted"),
                            ("tests_recorded", "Tests Recorded"),
                            ("results_recorded", "Results Recorded"),
                            ("results_sent", "Results Sent"),
                            ("closed", "Closed"),
                            ("canceled", "Canceled"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.case",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.consultant",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical visit",
                "verbose_name_plural": "historical visits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisitDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the document",
                        max_length=255,
                        verbose_name="Document Name",
                    ),
                ),
                (
                    "document",
                    models.TextField(
                        help_text="Document related to the visit",
                        max_length=100,
                        verbose_name="Document",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Uploaded At"
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document is hidden from clients",
                        verbose_name="Hidden",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who uploaded the document",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Visit Document",
                "verbose_name_plural": "historical Visit Documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisitNote",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Note content", max_length=2000, verbose_name="Note"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this note is hidden from clients",
                        verbose_name="Hidden",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who created the note",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sure.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Visit Note",
                "verbose_name_plural": "historical Visit Notes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
