# Generated by Django 5.2.8 on 2025-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0031_alter_visitdocument_options_alter_visitnote_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultinformation",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="resultinformation",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="resultinformation",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="resultinformation",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="resultinformation",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="resultinformation",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
    ]
