# Generated by Django 5.2.8 on 2025-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0032_resultinformation_information_text_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="name_de",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="name_en",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="name_es",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="name_fr",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="name_it",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="name_pt",
            field=models.CharField(
                help_text="Name of the questionnaire",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="description_de",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="description_fr",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="description_it",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="description_pt",
            field=models.TextField(
                blank=True,
                help_text="Description of the section",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="title_de",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="title_en",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="title_es",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="title_fr",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="title_it",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="title_pt",
            field=models.CharField(
                help_text="Title of the section",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
