# Generated by Django 5.2.8 on 2025-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0033_historicalquestionnaire_name_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_pt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="label_en",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="label_es",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="label_fr",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="label_it",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="label_pt",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="question_text_de",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="question_text_en",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="question_text_es",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="question_text_fr",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="question_text_it",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="question_text_pt",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="text_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="text_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="text_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="text_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="text_pt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Option Text"
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="label_en",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="label_es",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="label_fr",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="label_it",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="label_pt",
            field=models.CharField(
                blank=True,
                help_text="Short label for the question",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="question_text_de",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="question_text_en",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="question_text_es",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="question_text_fr",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="question_text_it",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="question_text_pt",
            field=models.TextField(null=True, verbose_name="Question Text"),
        ),
        migrations.AddField(
            model_name="historicalresultinformation",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicalresultinformation",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicalresultinformation",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicalresultinformation",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicalresultinformation",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicalresultinformation",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestkind",
            name="name_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="historicaltestkind",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="historicaltestkind",
            name="name_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="historicaltestkind",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="historicaltestkind",
            name="name_it",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="historicaltestkind",
            name="name_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Information text to be sent to the client",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="label_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="label_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="label_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="label_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="label_it",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="historicaltestresultoption",
            name="label_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="Label"),
        ),
    ]
