# Generated by Django 5.2.8 on 2025-12-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0034_historicalclientoption_text_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvisit",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published At"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published At"
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("tests_recorded", "Tests Recorded"),
                    ("results_recorded", "Results Recorded"),
                    ("results_sent", "Results Sent"),
                    ("results_missed", "Results Missed"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("tests_recorded", "Tests Recorded"),
                    ("results_recorded", "Results Recorded"),
                    ("results_sent", "Results Sent"),
                    ("results_missed", "Results Missed"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
