# Generated by Django 5.2.8 on 2025-12-03 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0035_historicalvisit_published_at_visit_published_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("tests_recorded", "Tests Recorded"),
                    ("results_recorded", "Results Recorded"),
                    ("results_sent", "Results Sent"),
                    ("results_missed", "Client missed results"),
                    ("results_seen", "Client accessed results"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("client_submitted", "Client Submitted"),
                    ("consultant_submitted", "Consultant Submitted"),
                    ("tests_recorded", "Tests Recorded"),
                    ("results_recorded", "Results Recorded"),
                    ("results_sent", "Results Sent"),
                    ("results_missed", "Client missed results"),
                    ("results_seen", "Client accessed results"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                ],
                default="created",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="VisitExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="The exported file containing visit data",
                        null=True,
                        upload_to="visit_exports/",
                        verbose_name="Exported File",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the export failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
