# Generated by Django 5.2.8 on 2025-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0036_alter_historicalvisit_status_alter_visit_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitexport",
            name="progress",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Progress of the export in percentage",
                verbose_name="Progress",
            ),
        ),
        migrations.AddField(
            model_name="visitexport",
            name="total_visits",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total number of visits included in the export",
                null=True,
                verbose_name="Total Visits",
            ),
        ),
    ]
