# Generated by Django 5.2.8 on 2025-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0037_visitexport_progress_visitexport_total_visits"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientquestion",
            name="extra_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is extra for centers",
                verbose_name="Extra for Centers",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="extra_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is extra for centers",
                verbose_name="Extra for Centers",
            ),
        ),
    ]
