# Generated by Django 5.2.8 on 2025-12-10 11:39

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0038_clientquestion_extra_for_centers_and_more"),
        ("tenants", "0013_location_included_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoption",
            name="choices_de",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="choices_en",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="choices_es",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="choices_fr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="choices_it",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="choices_pt",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices_de",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices_en",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices_es",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices_fr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices_it",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="choices_pt",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="choices_de",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="choices_en",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="choices_es",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="choices_fr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="choices_it",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="choices_pt",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="choices_de",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="choices_en",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="choices_es",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="choices_fr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="choices_it",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="choices_pt",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="clientquestion",
            name="extra_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is extra for centers, centers can opt-in to asking it.",
                verbose_name="Extra for Centers",
            ),
        ),
        migrations.AlterField(
            model_name="clientquestion",
            name="optional_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is optional for centers, centers can opt-out of asking it.",
                verbose_name="Optional for Centers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientquestion",
            name="extra_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is extra for centers, centers can opt-in to asking it.",
                verbose_name="Extra for Centers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientquestion",
            name="optional_for_centers",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is optional for centers, centers can opt-out of asking it.",
                verbose_name="Optional for Centers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresultinformation",
            name="option",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Select the result for which you want to display additional information",
                limit_choices_to={"information_by_sms": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sure.testresultoption",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisitdocument",
            name="document",
            field=models.TextField(
                help_text="Document related to the visit",
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                    )
                ],
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text_de",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text_es",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text_fr",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text_it",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="information_text_pt",
            field=models.TextField(
                blank=True,
                help_text="Detailed information related to this result option, the information about the result is already displayed, you only need to specify additional information (booking link, ...)",
                max_length=2000,
                null=True,
                verbose_name="Information Text",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="locations",
            field=models.ManyToManyField(
                help_text="Locations where this information is applicable. To show different texts at different locations create another entry for this location.",
                related_name="result_informations",
                to="tenants.location",
                verbose_name="Locations",
            ),
        ),
        migrations.AlterField(
            model_name="resultinformation",
            name="option",
            field=models.ForeignKey(
                help_text="Select the result for which you want to display additional information",
                limit_choices_to={"information_by_sms": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_informations",
                to="sure.testresultoption",
            ),
        ),
        migrations.AlterField(
            model_name="visitdocument",
            name="document",
            field=models.FileField(
                help_text="Document related to the visit",
                upload_to="visit_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                    )
                ],
                verbose_name="Document",
            ),
        ),
    ]
