# Generated by Django 5.2.8 on 2025-12-10 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0039_clientoption_choices_de_clientoption_choices_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testbundle",
            options={
                "ordering": ["name"],
                "verbose_name": "Test Bundle",
                "verbose_name_plural": "Test Bundles",
            },
        ),
    ]
