# Generated by Django 5.2.8 on 2025-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0040_alter_testbundle_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientquestion",
            name="use_textarea",
            field=models.BooleanField(
                default=False,
                help_text="Use a textarea instead of a single-line input for text responses",
                verbose_name="Use Textarea",
            ),
        ),
        migrations.AddField(
            model_name="consultantquestion",
            name="use_textarea",
            field=models.BooleanField(
                default=False,
                help_text="Use a textarea instead of a single-line input for text responses",
                verbose_name="Use Textarea",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientquestion",
            name="use_textarea",
            field=models.BooleanField(
                default=False,
                help_text="Use a textarea instead of a single-line input for text responses",
                verbose_name="Use Textarea",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantquestion",
            name="use_textarea",
            field=models.BooleanField(
                default=False,
                help_text="Use a textarea instead of a single-line input for text responses",
                verbose_name="Use Textarea",
            ),
        ),
    ]
