# Generated by Django 5.2.8 on 2025-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0041_clientquestion_use_textarea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Preferred language of the client",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Preferred language of the client",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
