# Generated by Django 5.2.9 on 2025-12-15 09:29

import django.core.validators
import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0042_case_language_historicalcase_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvisitdocument",
            name="document",
            field=models.TextField(
                help_text="Document related to the visit",
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="visitdocument",
            name="document",
            field=models.FileField(
                help_text="Document related to the visit",
                upload_to="visit_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Document",
            ),
        ),
    ]
