# Generated by Django 6.0 on 2025-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0043_alter_historicalvisitdocument_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant_de",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant_en",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant_es",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant_fr",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant_it",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="clientoption",
            name="text_for_consultant_pt",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_for_consultant_de",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_for_consultant_en",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_for_consultant_es",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_for_consultant_fr",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_for_consultant_it",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="text_for_consultant_pt",
            field=models.CharField(
                blank=True,
                help_text="Text to be shown to the consultant when this option is selected",
                max_length=255,
                null=True,
                verbose_name="Text for Consultant",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="label_en",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="label_es",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="label_fr",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="label_it",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="historicalsection",
            name="label_pt",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label_de",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label_en",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label_es",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label_fr",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label_it",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label_pt",
            field=models.CharField(
                blank=True,
                help_text="Short label for the section",
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
    ]
