# Generated by Django 6.0.1 on 2026-01-14 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0044_clientoption_text_for_consultant_de_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientanswer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded the answer (consultant)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="consultantanswer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded the answer (consultant)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="freeformtest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded the free form test",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded the test",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded the test result (consultant)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="visitdocument",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who uploaded the document",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="visitexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visit_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visitlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed the action",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="visitnote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created the note",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
