# Generated by Django 6.0.1 on 2026-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0045_alter_clientanswer_user_alter_consultantanswer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvisit",
            name="no_reminder",
            field=models.BooleanField(
                default=False,
                help_text="Whether to skip sending reminders for this visit",
                verbose_name="No Reminder",
            ),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the reminder was sent",
                null=True,
                verbose_name="Reminder Sent At",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="no_reminder",
            field=models.BooleanField(
                default=False,
                help_text="Whether to skip sending reminders for this visit",
                verbose_name="No Reminder",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the reminder was sent",
                null=True,
                verbose_name="Reminder Sent At",
            ),
        ),
    ]
