# Generated by Django 6.0.1 on 2026-01-20 08:24

import django.core.validators
import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0046_historicalvisit_no_reminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="client_pdf",
            field=models.TextField(
                blank=True,
                help_text="PDF file for the client questionnaire",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Client PDF",
            ),
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="consultant_pdf",
            field=models.TextField(
                blank=True,
                help_text="PDF file for the consultant questionnaire",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Consultant PDF",
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="client_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF file for the client questionnaire",
                null=True,
                upload_to="questionnaire_pdfs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Client PDF",
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="consultant_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF file for the consultant questionnaire",
                null=True,
                upload_to="questionnaire_pdfs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Consultant PDF",
            ),
        ),
    ]
