# Generated by Django 6.0.1 on 2026-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0049_visitexportdownload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the contact is active",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=30),
        ),
    ]
