# Generated by Django 6.0.2 on 2026-02-09 20:41

import sure.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0050_remove_contact_email_contact_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                default=sure.models.generate_token, max_length=64, verbose_name="Token"
            ),
        ),
    ]
