# Generated by Django 6.0.3 on 2026-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0051_alter_token_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="note_lab",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from the lab about the test result",
                max_length=2000,
                verbose_name="Lab Note",
            ),
        ),
    ]
