# Generated by Django 6.0.5 on 2026-05-21 11:59

import django.core.validators
import django_clamd.validators
import sure.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0052_testresult_note_lab"),
        ("tenants", "0027_remove_advertisement_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="locations",
            field=models.ManyToManyField(
                related_name="questionnaires",
                to="tenants.location",
                verbose_name="Locations",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisitdocument",
            name="document",
            field=models.TextField(
                help_text="Document related to the visit",
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                    ),
                    sure.validators.MimeTypeValidator(
                        allowed_mimetypes=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "image/jpeg",
                            "image/png",
                        ]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="visitdocument",
            name="document",
            field=models.FileField(
                help_text="Document related to the visit",
                upload_to="visit_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                    ),
                    sure.validators.MimeTypeValidator(
                        allowed_mimetypes=[
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "image/jpeg",
                            "image/png",
                        ]
                    ),
                    django_clamd.validators.validate_file_infection,
                ],
                verbose_name="Document",
            ),
        ),
    ]
