# Generated by Django 6.0.5 on 2026-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sure", "0053_questionnaire_locations_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "ordering": ["order"],
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order of the questionnaire in the list of questionnaires",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order of the questionnaire in the list of questionnaires",
                verbose_name="Order",
            ),
        ),
    ]
