# Generated by Django 6.0.5 on 2026-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0054_alter_questionnaire_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoption",
            name="exclusive",
            field=models.BooleanField(
                default=False,
                help_text="If checked, all other options are disabled when this option is selected",
                verbose_name="Exclusive",
            ),
        ),
        migrations.AddField(
            model_name="consultantoption",
            name="exclusive",
            field=models.BooleanField(
                default=False,
                help_text="If checked, all other options are disabled when this option is selected",
                verbose_name="Exclusive",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientoption",
            name="exclusive",
            field=models.BooleanField(
                default=False,
                help_text="If checked, all other options are disabled when this option is selected",
                verbose_name="Exclusive",
            ),
        ),
        migrations.AddField(
            model_name="historicalconsultantoption",
            name="exclusive",
            field=models.BooleanField(
                default=False,
                help_text="If checked, all other options are disabled when this option is selected",
                verbose_name="Exclusive",
            ),
        ),
    ]
