# Generated by Django 6.0.7 on 2026-09-01 12:36

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0055_clientoption_exclusive_consultantoption_exclusive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"base_manager_name": "all_objects"},
        ),
        migrations.AlterModelManagers(
            name="test",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when the test was marked as deleted",
                null=True,
                verbose_name="Deleted At",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who marked the test as deleted",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
    ]
