# Generated by Django 6.0.7 on 2026-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sure", "0056_test_soft_delete"),
        ("tenants", "0027_remove_advertisement_severity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="questionnaires",
                to="tenants.location",
                verbose_name="Locations",
            ),
        ),
    ]
