# Generated by Django 6.0.1 on 2026-01-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sure", "0050_remove_contact_email_contact_active_and_more"),
        ("tenants", "0024_historicallocation_reminder_text_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LabOrderCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_number",
                    models.CharField(help_text="e.g. 0001297740", max_length=50),
                ),
                ("last_index", models.PositiveIntegerField(default=0)),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="lab_order_counters", to="tenants.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="sure.visit",
                    ),
                ),
                (
                    "lab_order_counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labor.labordercounter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationToLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_code", models.CharField(max_length=100)),
                (
                    "nr_kreis",
                    models.CharField(blank=True, help_text="e.g. 9610", max_length=10),
                ),
                (
                    "labor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labor.laboratory",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=255)),
                ("profile_code", models.CharField(max_length=50)),
                (
                    "result_label",
                    models.CharField(
                        blank=True,
                        help_text="Label in HL7 result (OBX-3)",
                        max_length=100,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, help_text="e.g. Serum, EDTA", max_length=50
                    ),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, help_text="e.g. S", max_length=10),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labor.laboratory",
                    ),
                ),
                (
                    "test_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sure.testkind"
                    ),
                ),
            ],
        ),
    ]
