# Generated by Django 6.0.1 on 2026-01-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FTPConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sftp", models.BooleanField(default=True)),
                ("host", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("upload_directory", models.CharField(max_length=255)),
                ("results_directory", models.CharField(max_length=255)),
                (
                    "laboratory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labor.laboratory",
                    ),
                ),
            ],
        ),
    ]
