# Generated by Django 6.0.1 on 2026-02-02 09:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0002_ftpconnection"),
        ("sure", "0050_remove_contact_email_contact_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ftpconnection",
            options={
                "verbose_name": "FTP Connection",
                "verbose_name_plural": "FTP Connections",
            },
        ),
        migrations.AlterModelOptions(
            name="laboratory",
            options={
                "verbose_name": "Laboratory",
                "verbose_name_plural": "Laboratories",
            },
        ),
        migrations.AlterModelOptions(
            name="laborder",
            options={"verbose_name": "Lab Order", "verbose_name_plural": "Lab Orders"},
        ),
        migrations.AlterModelOptions(
            name="labordercounter",
            options={
                "verbose_name": "Lab Order Counter",
                "verbose_name_plural": "Lab Order Counters",
            },
        ),
        migrations.AlterModelOptions(
            name="locationtolab",
            options={
                "verbose_name": "Location to Laboratory Mapping",
                "verbose_name_plural": "Location to Laboratory Mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="testprofile",
            options={
                "verbose_name": "Test Profile",
                "verbose_name_plural": "Test Profiles",
            },
        ),
        migrations.AddField(
            model_name="laborder",
            name="codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of material codes",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="content",
            field=models.TextField(blank=True, help_text="HL7 Order content"),
        ),
        migrations.AddField(
            model_name="laborder",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("sent", "Sent"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="generated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="labordercounter",
            name="nr_kreis",
            field=models.CharField(
                blank=True, help_text="e.g. 9610", max_length=10, unique=True
            ),
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.TextField(blank=True, help_text="HL7 Result content"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="labor.laborder",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="sure.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Result",
                "verbose_name_plural": "Lab Results",
            },
        ),
    ]
