# Generated by Django 6.0.1 on 2026-02-02 09:23

import labor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0003_alter_ftpconnection_options_alter_laboratory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labordercounter",
            name="locations",
        ),
        migrations.AlterField(
            model_name="locationtolab",
            name="nr_kreis",
            field=models.CharField(
                blank=True,
                help_text="e.g. 9610",
                max_length=10,
                validators=[labor.models.validate_nr_kreis],
            ),
        ),
    ]
