# Generated by Django 6.0.2 on 2026-02-09 08:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0005_historicalftpconnection_historicallaborder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallaborder",
            name="profiles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of test profiles included in the order",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="price_kk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="price_vct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="profiles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of test profiles included in the order",
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="price_kk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="price_vct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
