# Generated by Django 6.0.2 on 2026-02-16 12:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0006_historicallaborder_profiles_and_more"),
        ("sure", "0050_remove_contact_email_contact_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltestprofile",
            name="material",
        ),
        migrations.RemoveField(
            model_name="historicaltestprofile",
            name="material_code",
        ),
        migrations.RemoveField(
            model_name="testprofile",
            name="material",
        ),
        migrations.RemoveField(
            model_name="testprofile",
            name="material_code",
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="material_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                help_text="List of material codes (e.g. S, EDTA)",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="materials",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of required materials (e.g. Serum, EDTA)",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="n_materials",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of materials required for this test profile",
            ),
        ),
        migrations.AddField(
            model_name="historicaltestprofile",
            name="require_additional",
            field=models.BooleanField(
                default=False,
                help_text="Whether additional information is required for this test profile",
            ),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="implementation",
            field=models.CharField(
                choices=[("team_w", "Team W"), ("unilabs", "Unilabs")],
                default="team_w",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_laboratories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="material_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                help_text="List of material codes (e.g. S, EDTA)",
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="materials",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of required materials (e.g. Serum, EDTA)",
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="n_materials",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of materials required for this test profile",
            ),
        ),
        migrations.AddField(
            model_name="testprofile",
            name="require_additional",
            field=models.BooleanField(
                default=False,
                help_text="Whether additional information is required for this test profile",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Laboratory offering this test profile",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="labor.laboratory",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="note",
            field=models.TextField(
                blank=True, help_text="Additional notes about the test profile"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="price_kk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for statutory health insurance (KK)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="price_vct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for private patients (VCT)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="profile_code",
            field=models.CharField(
                help_text="Code of the test profile (lab)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="profile_name",
            field=models.CharField(
                help_text="Name of the test profile (lab)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestprofile",
            name="test_kind",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Test kind associated with this profile",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sure.testkind",
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="laboratory",
            field=models.ForeignKey(
                help_text="Laboratory offering this test profile",
                on_delete=django.db.models.deletion.CASCADE,
                to="labor.laboratory",
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="note",
            field=models.TextField(
                blank=True, help_text="Additional notes about the test profile"
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="price_kk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for statutory health insurance (KK)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="price_vct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for private patients (VCT)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="profile_code",
            field=models.CharField(
                help_text="Code of the test profile (lab)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="profile_name",
            field=models.CharField(
                help_text="Name of the test profile (lab)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="testprofile",
            name="test_kind",
            field=models.ForeignKey(
                help_text="Test kind associated with this profile",
                on_delete=django.db.models.deletion.CASCADE,
                to="sure.testkind",
            ),
        ),
    ]
