# Generated by Django 6.0.2 on 2026-02-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0007_remove_historicaltestprofile_material_and_more"),
        ("sure", "0050_remove_contact_email_contact_active_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="testprofile",
            constraint=models.UniqueConstraint(
                fields=("laboratory", "test_kind"),
                name="unique_test_profile_per_laboratory_and_test_kind",
            ),
        ),
    ]
