# Generated by Django 6.0.2 on 2026-02-16 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0008_testprofile_unique_test_profile_per_laboratory_and_test_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallaborder",
            name="materials",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of materials required for the order",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="materials",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of materials required for the order",
            ),
        ),
    ]
