# Generated by Django 6.0.2 on 2026-02-16 13:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labor", "0009_historicallaborder_materials_laborder_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallaborder",
            name="note",
            field=models.TextField(
                blank=True, help_text="Additional notes for the lab order"
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="note",
            field=models.TextField(
                blank=True, help_text="Additional notes for the lab order"
            ),
        ),
        migrations.CreateModel(
            name="APIConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_url", models.URLField()),
                ("api_key", models.CharField(max_length=255)),
                (
                    "laboratory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labor.laboratory",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Connection",
                "verbose_name_plural": "API Connections",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAPIConnection",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("api_url", models.URLField()),
                ("api_key", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="labor.laboratory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical API Connection",
                "verbose_name_plural": "historical API Connections",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HL7Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="HL7 Result content"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hl7_results",
                        to="labor.laboratory",
                    ),
                ),
            ],
        ),
    ]
