# Generated by Django 5.2.3 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labor", "0010_historicallaborder_note_laborder_note_apiconnection_and_more"),
        ("sure", "0051_alter_token_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_text", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_mappings",
                        to="labor.testprofile",
                    ),
                ),
                (
                    "result_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sure.testresultoption",
                    ),
                ),
            ],
        ),
    ]
