# Generated by Django 6.0.3 on 2026-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labor", "0012_testprofile_fallback_result_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="hl7result",
            name="logs",
            field=models.TextField(blank=True, help_text="Processing logs and errors"),
        ),
    ]
